//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITela
{
    
    
    /// <summary>
    /// 
    /// </summary>
    public class CountryRecord : ITela.CodeValue
    {
        
        public string Alpha2Code { get; private set; }
        
        public string Name { get; private set; }
        
        public CountryRecord(string alpha2Code, string name) : 
                base(alpha2Code, name)
        {
            this.Alpha2Code = alpha2Code;
            this.Name = name;
        }
    }
}
