//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITela.Gc
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    public class TransportationStatus : ITela.ICodeValueCollectionable
    {
        
        public static Dictionary<string, TransportationStatusRecord> DATA
        {
            get
            {
                var dict = new Dictionary<string, TransportationStatusRecord>();
                dict.Add("1", new TransportationStatusRecord("1", "Arrival, completed"));
                dict["1"].description = "The goods/consignment/equipment/means of transport has arrived.";
                dict.Add("2", new TransportationStatusRecord("2", "Loading, authorized"));
                dict["2"].description = "Authorisation to load has been given.";
                dict.Add("3", new TransportationStatusRecord("3", "Arrival, in defective condition"));
                dict["3"].description = "The goods/consignment/equipment or a means of transport has arrived in a defectiv" +
                    "e condition.";
                dict.Add("4", new TransportationStatusRecord("4", "Defective equipment returned to service"));
                dict["4"].description = "The equipment previously the subject of a \'defective condition\' status has been r" +
                    "eturned to service.";
                dict.Add("5", new TransportationStatusRecord("5", "Process, begun"));
                dict["5"].description = "The process has begun.";
                dict.Add("6", new TransportationStatusRecord("6", "Booking, completed"));
                dict["6"].description = "The goods/consignment/equipment or means of transport has been booked.";
                dict.Add("7", new TransportationStatusRecord("7", "Booking, cancelled"));
                dict["7"].description = "The booking of goods/consignment/equipment or means of transport has been cancell" +
                    "ed.";
                dict.Add("8", new TransportationStatusRecord("8", "Cleared, import restrictions"));
                dict["8"].description = "The goods/consignment/equipment/means of transport held for import restriction pu" +
                    "rposes, has been released for import.";
                dict.Add("9", new TransportationStatusRecord("9", "Cleared, export restrictions"));
                dict["9"].description = "The goods/consignment/equipment/means of transport held for export restriction pu" +
                    "rposes, has been released for export.";
                dict.Add("10", new TransportationStatusRecord("10", "Cleared, by agriculture, food or fisheries authorities"));
                dict["10"].description = "The goods/consignment/equipment/means of transport has been cleared by agricultur" +
                    "e, food or fisheries authorities.";
                dict.Add("11", new TransportationStatusRecord("11", "Cleared, by port authority"));
                dict["11"].description = "The goods/consignment/equipment/means of transport has been cleared by port autho" +
                    "rity.";
                dict.Add("12", new TransportationStatusRecord("12", "Cleared, by customs"));
                dict["12"].description = "The goods/consignment/equipment/means of transport has been cleared by customs.";
                dict.Add("13", new TransportationStatusRecord("13", "Collection/pick-up, completed"));
                dict["13"].description = "The goods/consignment/equipment has been collected/picked-up.";
                dict.Add("14", new TransportationStatusRecord("14", "Process, completed"));
                dict["14"].description = "The process has been completed.";
                dict.Add("15", new TransportationStatusRecord("15", "Consolidated"));
                dict["15"].description = "The goods/consignments have been consolidated.";
                dict.Add("16", new TransportationStatusRecord("16", "Crossed border"));
                dict["16"].description = "The goods/consignments/equipment/means of transport has crossed a border.";
                dict.Add("17", new TransportationStatusRecord("17", "Customs clearance, refused"));
                dict["17"].description = "The goods/consignment/equipment/means of transport has been refused to be cleared" +
                    " by the customs authorities.";
                dict.Add("18", new TransportationStatusRecord("18", "Damaged in the course of transportation"));
                dict["18"].description = "The goods/consignment/equipment has been damaged in the course of transportation." +
                    "";
                dict.Add("19", new TransportationStatusRecord("19", "Equipment, damage quoted for"));
                dict["19"].description = "Damaged equipment has been assessed and a repair quotation has been sent.";
                dict.Add("20", new TransportationStatusRecord("20", "Delayed, in the course of transportation"));
                dict["20"].description = "The goods/consignment/equipment/means of transport has been delayed in the course" +
                    " of transportation.";
                dict.Add("21", new TransportationStatusRecord("21", "Delivery, completed"));
                dict["21"].description = "The goods/consignment/equipment has been delivered.";
                dict.Add("22", new TransportationStatusRecord("22", "Delivery, completed as per instruction"));
                dict["22"].description = "Delivery of the goods/consignment/equipment has been completed as per instruction" +
                    ".";
                dict.Add("23", new TransportationStatusRecord("23", "Delivery, not completed"));
                dict["23"].description = "Delivery of the goods/consignment/equipment has not been completed.";
                dict.Add("24", new TransportationStatusRecord("24", "Departure, completed"));
                dict["24"].description = "The means of transport has departed.";
                dict.Add("25", new TransportationStatusRecord("25", "Departure, delayed"));
                dict["25"].description = "The means of transport has been delayed in departure.";
                dict.Add("26", new TransportationStatusRecord("26", "Deramped"));
                dict["26"].description = "The equipment has been removed from a position above another type of equipment an" +
                    "d/or on a means of transport.";
                dict.Add("27", new TransportationStatusRecord("27", "Despatch, completed"));
                dict["27"].description = "The goods/consignment/equipment has been despatched.";
                dict.Add("28", new TransportationStatusRecord("28", "Stripped"));
                dict["28"].description = "The goods/consignment/equipment has been unloaded from a piece of equipment in wh" +
                    "ich they were transported.";
                dict.Add("29", new TransportationStatusRecord("29", "Unloaded"));
                dict["29"].description = "The goods/consignment/equipment has been unloaded from a means of transport.";
                dict.Add("30", new TransportationStatusRecord("30", "Empty on inspection"));
                dict["30"].description = "The package/equipment has been found to be empty on inspection.";
                dict.Add("31", new TransportationStatusRecord("31", "En route"));
                dict["31"].description = "The goods/consignment/equipment/means of transport is moving to destination.";
                dict.Add("32", new TransportationStatusRecord("32", "Equipment, returned from repair"));
                dict["32"].description = "The equipment has been returned from repair.";
                dict.Add("33", new TransportationStatusRecord("33", "Equipment, sent for repair"));
                dict["33"].description = "The equipment has been sent for repair.";
                dict.Add("34", new TransportationStatusRecord("34", "Equipment, repaired"));
                dict["34"].description = "The equipment has been repaired.";
                dict.Add("35", new TransportationStatusRecord("35", "Forwarded to destination"));
                dict["35"].description = "The goods/consignment/equipment has been forwarded to a destination.";
                dict.Add("36", new TransportationStatusRecord("36", "Not found"));
                dict["36"].description = "The goods/consignment/equipment/means of transport has not been found.";
                dict.Add("37", new TransportationStatusRecord("37", "Found"));
                dict["37"].description = "The goods/consignment/equipment/means of transport has been found.";
                dict.Add("38", new TransportationStatusRecord("38", "Freight paid"));
                dict["38"].description = "The freight charges have been paid.";
                dict.Add("39", new TransportationStatusRecord("39", "Released from bond"));
                dict["39"].description = "The goods/consignment/equipment has been released from bond.";
                dict.Add("40", new TransportationStatusRecord("40", "Arrival, at port"));
                dict["40"].description = "The goods/consignment/equipment has arrived at the port.";
                dict.Add("41", new TransportationStatusRecord("41", "Handed over under continued responsibility"));
                dict["41"].description = "The goods/consignment/equipment has been handed over under responsibility of the " +
                    "same transport operator.";
                dict.Add("44", new TransportationStatusRecord("44", "Misrouted consignment corrected"));
                dict["44"].description = "The goods/consignment/equipment/means of transport has been re-routed to the corr" +
                    "ect destination.";
                dict.Add("45", new TransportationStatusRecord("45", "Arrival, consignee informed"));
                dict["45"].description = "The consignee has been informed of the arrival of the goods/consignments/equipmen" +
                    "t/means of transport.";
                dict.Add("46", new TransportationStatusRecord("46", "Moved, into bond"));
                dict["46"].description = "The goods/consignment/equipment has been moved into bond.";
                dict.Add("47", new TransportationStatusRecord("47", "Moved, into packing depot"));
                dict["47"].description = "The goods/consignment/equipment has been moved into a packing depot.";
                dict.Add("48", new TransportationStatusRecord("48", "Loading, completed onto a means of transport"));
                dict["48"].description = "The goods/consignment/equipment has been loaded onto a means of transport.";
                dict.Add("49", new TransportationStatusRecord("49", "Lost"));
                dict["49"].description = "The goods/consignment/equipment/means of transport has been lost .";
                dict.Add("50", new TransportationStatusRecord("50", "Manifested"));
                dict["50"].description = "The goods/consignment/equipment has been included on a manifest .";
                dict.Add("51", new TransportationStatusRecord("51", "Onloaded from a means of transport"));
                dict["51"].description = "The consignment has been onloaded from a means of transport.";
                dict.Add("53", new TransportationStatusRecord("53", "Collection/pick-up, not completed"));
                dict["53"].description = "The goods/consignment/equipment expected has not been collected/picked-up.";
                dict.Add("54", new TransportationStatusRecord("54", "Unidentifiable"));
                dict["54"].description = "The goods/consignment/equipment/means of transport cannot be identified.";
                dict.Add("57", new TransportationStatusRecord("57", "Not loaded onto a means of transport"));
                dict["57"].description = "The goods/consignment/equipment has not been loaded onto a means of transport.";
                dict.Add("58", new TransportationStatusRecord("58", "Equipment, off hire"));
                dict["58"].description = "The equipment is no longer under lease.";
                dict.Add("59", new TransportationStatusRecord("59", "Premature onloading"));
                dict["59"].description = "The goods/consignment/equipment has been onloaded prematurely from a means of tra" +
                    "nsport.";
                dict.Add("60", new TransportationStatusRecord("60", "Equipment, on hire"));
                dict["60"].description = "The equipment has been leased.";
                dict.Add("61", new TransportationStatusRecord("61", "Outstanding claims settled"));
                dict["61"].description = "Outstanding claims in respect of the goods/consignment/equipment have been settle" +
                    "d.";
                dict.Add("62", new TransportationStatusRecord("62", "Overlanded"));
                dict["62"].description = "Unmanifested goods/consignments/equipment has been unloaded.";
                dict.Add("63", new TransportationStatusRecord("63", "Not available for collection/pick-up"));
                dict["63"].description = "The goods/consignment/equipment is not available for collection/pick-up.";
                dict.Add("64", new TransportationStatusRecord("64", "Collection/pick-up, awaited"));
                dict["64"].description = "The goods/consignment/equipment is awaiting collection/pick-up.";
                dict.Add("65", new TransportationStatusRecord("65", "Equipment, plugged-in"));
                dict["65"].description = "The equipment has been plugged into a power source.";
                dict.Add("66", new TransportationStatusRecord("66", "Plundered"));
                dict["66"].description = "The goods/consignment/equipment/means of transport has been plundered.";
                dict.Add("67", new TransportationStatusRecord("67", "Positioned"));
                dict["67"].description = "The goods/consignment/equipment has been positioned .";
                dict.Add("68", new TransportationStatusRecord("68", "Pre-informed"));
                dict["68"].description = "The party has been informed  in advance.";
                dict.Add("69", new TransportationStatusRecord("69", "Disposed of"));
                dict.Add("70", new TransportationStatusRecord("70", "Ramped equipment"));
                dict["70"].description = "The equipment has been placed above another type of equipment and/or placed on a " +
                    "means of transport.";
                dict.Add("71", new TransportationStatusRecord("71", "Ready for transportation"));
                dict["71"].description = "The goods/consignment/equipment is ready for transportation.";
                dict.Add("72", new TransportationStatusRecord("72", "Receipt of goods fully acknowledged"));
                dict["72"].description = "The receipt of goods has been fully acknowledged.";
                dict.Add("73", new TransportationStatusRecord("73", "Receipt of goods partially acknowledged"));
                dict["73"].description = "The receipt of goods has been partially acknowledged.";
                dict.Add("74", new TransportationStatusRecord("74", "Received"));
                dict["74"].description = "The goods/consignment/equipment have been received .";
                dict.Add("75", new TransportationStatusRecord("75", "Consignee changed"));
                dict["75"].description = "The consignee has been changed.";
                dict.Add("76", new TransportationStatusRecord("76", "Transport re-arranged"));
                dict["76"].description = "The transport of the goods/consignment/equipment has been re-arranged.";
                dict.Add("77", new TransportationStatusRecord("77", "Refused, action"));
                dict["77"].description = "The transport action has been refused.";
                dict.Add("78", new TransportationStatusRecord("78", "Released"));
                dict["78"].description = "The goods/consignment/equipment has been released .";
                dict.Add("79", new TransportationStatusRecord("79", "Reloaded onto a means of transport"));
                dict["79"].description = "The goods/consignment/equipment has been reloaded onto a means of transport.";
                dict.Add("80", new TransportationStatusRecord("80", "Returned as instructed"));
                dict["80"].description = "The goods/consignment/equipment has been returned  as  instructed.";
                dict.Add("81", new TransportationStatusRecord("81", "Returned wrecked"));
                dict["81"].description = "The goods/consignment/equipment/means of transport has been returned in a wrecked" +
                    " condition .";
                dict.Add("82", new TransportationStatusRecord("82", "Returned"));
                dict["82"].description = "The goods/consignment/equipment has been returned .";
                dict.Add("83", new TransportationStatusRecord("83", "Sealed equipment"));
                dict["83"].description = "The equipment has been sealed.";
                dict.Add("84", new TransportationStatusRecord("84", "Service ordered"));
                dict["84"].description = "A service has been ordered.";
                dict.Add("85", new TransportationStatusRecord("85", "Short landed"));
                dict["85"].description = "Goods/consignments/equipment manifested for unloading have not been unloaded.";
                dict.Add("86", new TransportationStatusRecord("86", "Short shipped"));
                dict["86"].description = "The goods/consignment/equipment expected to be sent has not been fully loaded ont" +
                    "o a means of transport.";
                dict.Add("87", new TransportationStatusRecord("87", "Despatched, completed via a wrong route"));
                dict["87"].description = "The goods/consignment/equipment has been despatched via a wrong route.";
                dict.Add("88", new TransportationStatusRecord("88", "Split consignment"));
                dict["88"].description = "The consignment of goods has been split";
                dict.Add("89", new TransportationStatusRecord("89", "Steam cleaned"));
                dict["89"].description = "The goods/equipment has been steam cleaned.";
                dict.Add("90", new TransportationStatusRecord("90", "Movement stopped"));
                dict["90"].description = "The movement of the goods/consignment/equipment has been stopped .";
                dict.Add("91", new TransportationStatusRecord("91", "Stored"));
                dict["91"].description = "The goods/consignment/equipment has been placed into storage.";
                dict.Add("92", new TransportationStatusRecord("92", "Stowed"));
                dict["92"].description = "The goods/consignment/equipment has been placed on a means of transport.";
                dict.Add("93", new TransportationStatusRecord("93", "Stuffed"));
                dict["93"].description = "The goods/consignments have been loaded into a piece of equipment.";
                dict.Add("94", new TransportationStatusRecord("94", "Stuffed and sealed"));
                dict["94"].description = "The goods/consignments have been loaded into a piece of equipment and the equipme" +
                    "nt has been sealed.";
                dict.Add("95", new TransportationStatusRecord("95", "Sub-lease notice in"));
                dict["95"].description = "A sub-lease notice has been sent to the lessor.";
                dict.Add("96", new TransportationStatusRecord("96", "Sub-lease notice out"));
                dict["96"].description = "A sub-lease notice has been sent by the lessee.";
                dict.Add("97", new TransportationStatusRecord("97", "Damage surveyed"));
                dict["97"].description = "The goods/consignment/equipment has been  surveyed  to assess the damage.";
                dict.Add("98", new TransportationStatusRecord("98", "Transferred in"));
                dict["98"].description = "The goods/consignment/equipment has been transferred in .";
                dict.Add("99", new TransportationStatusRecord("99", "Transferred out"));
                dict["99"].description = "The goods/consignment/equipment has been transferred out .";
                dict.Add("100", new TransportationStatusRecord("100", "Transshipment"));
                dict["100"].description = "The goods/consignment/equipment has been transferred to another means of transpor" +
                    "t.";
                dict.Add("101", new TransportationStatusRecord("101", "Delayed in transit"));
                dict["101"].description = "The goods/consignment/equipment/means of transport has been delayed in transit.";
                dict.Add("102", new TransportationStatusRecord("102", "Unknown"));
                dict["102"].description = "The goods/consignment/equipment/means of transport is not known .";
                dict.Add("103", new TransportationStatusRecord("103", "Equipment, unplugged"));
                dict["103"].description = "The equipment has been removed from the  power source.";
                dict.Add("104", new TransportationStatusRecord("104", "Delivery refused, to be re-arranged"));
                dict["104"].description = "The delivery of the goods has been refused and is to be re-arranged.";
                dict.Add("105", new TransportationStatusRecord("105", "Delivery, postponed"));
                dict["105"].description = "A part or the whole of the delivery is postponed.";
                dict.Add("106", new TransportationStatusRecord("106", "Delivery refused"));
                dict["106"].description = "A part or the whole of the delivery is refused.";
                dict.Add("107", new TransportationStatusRecord("107", "Anomaly on arrival"));
                dict["107"].description = "An anomaly has been found on arrival .";
                dict.Add("108", new TransportationStatusRecord("108", "Delivery claim"));
                dict["108"].description = "A claim has been made at delivery.";
                dict.Add("109", new TransportationStatusRecord("109", "Delivery, impossible, delivery notice left"));
                dict["109"].description = "Delivery has not been possible, a delivery notice has been left.";
                dict.Add("110", new TransportationStatusRecord("110", "Delivery, impossible, no delivery notice left"));
                dict["110"].description = "Delivery has not been possible, no delivery notice has been left.";
                dict.Add("111", new TransportationStatusRecord("111", "Transport terminated"));
                dict["111"].description = "The transport of the goods/consignment/equipment/means of transport has been term" +
                    "inated.";
                dict.Add("112", new TransportationStatusRecord("112", "Held, at consignee\'s disposal"));
                dict["112"].description = "The goods/consignment is held at consignee\'s disposal";
                dict.Add("113", new TransportationStatusRecord("113", "Delivery, in progress"));
                dict["113"].description = "The delivery of the goods/consignment is in progress.";
                dict.Add("114", new TransportationStatusRecord("114", "Delivery, accepted subject to further inspection"));
                dict["114"].description = "Delivery accepted subject to further inspection of the goods/consignment/equipmen" +
                    "t/means of transport.";
                dict.Add("115", new TransportationStatusRecord("115", "Discrepancy"));
                dict["115"].description = "There is a discrepancy in the details.";
                dict.Add("116", new TransportationStatusRecord("116", "Export inhibited"));
                dict["116"].description = "Export is inhibited.";
                dict.Add("117", new TransportationStatusRecord("117", "Missing"));
                dict["117"].description = "The goods/consignment/equipment is missing.";
                dict.Add("118", new TransportationStatusRecord("118", "Stowed on deck"));
                dict["118"].description = "The goods/consignment/equipment has been stowed on/above deck.";
                dict.Add("119", new TransportationStatusRecord("119", "Unable to be located"));
                dict["119"].description = "The goods/consignment/equipment cannot be located.";
                dict.Add("120", new TransportationStatusRecord("120", "Unacceptable condition"));
                dict["120"].description = "The goods/consignment/equipment/means of transport is in an unacceptable conditio" +
                    "n .";
                dict.Add("121", new TransportationStatusRecord("121", "Stowed under deck"));
                dict["121"].description = "The goods/consignment/equipment has been stowed under/below deck.";
                dict.Add("123", new TransportationStatusRecord("123", "Accompanying documents delivered"));
                dict["123"].description = "All documents accompanying the cargo have been delivered .";
                dict.Add("124", new TransportationStatusRecord("124", "For transfer"));
                dict["124"].description = "The goods/consignment/equipment is to be transferred.";
                dict.Add("125", new TransportationStatusRecord("125", "No status"));
                dict["125"].description = "No status information is available.";
                dict.Add("126", new TransportationStatusRecord("126", "Customs clearance, in progress"));
                dict["126"].description = "Customs clearance is in progress.";
                dict.Add("127", new TransportationStatusRecord("127", "Departed, completed on a means of transport"));
                dict["127"].description = "The goods/consignment/equipment has departed on a means of transport.";
                dict.Add("128", new TransportationStatusRecord("128", "Awaiting customs import release"));
                dict["128"].description = "Awaiting customs release for import.";
                dict.Add("129", new TransportationStatusRecord("129", "In-bond movement"));
                dict["129"].description = "The goods/consignment/equipment are moving under bond .";
                dict.Add("130", new TransportationStatusRecord("130", "Consignment received from shipper"));
                dict["130"].description = "The consignment has been received from shipper.";
                dict.Add("131", new TransportationStatusRecord("131", "For transfer, to another carrier"));
                dict["131"].description = "The goods/consignment/equipment is to be transferred to another carrier.";
                dict.Add("132", new TransportationStatusRecord("132", "Loading, in progress"));
                dict["132"].description = "The goods/consignment/equipment is being loaded onto a means of transport.";
                dict.Add("133", new TransportationStatusRecord("133", "Special loading operations"));
                dict["133"].description = "Operations related to special loading of goods/consignment/equipment .";
                dict.Add("134", new TransportationStatusRecord("134", "Embarking passengers"));
                dict["134"].description = "The embarkation of passengers.";
                dict.Add("135", new TransportationStatusRecord("135", "Unloading, in progress"));
                dict["135"].description = "The goods/consignment/equipment is being unloaded from a means of transport.";
                dict.Add("136", new TransportationStatusRecord("136", "Special unloading"));
                dict["136"].description = "Operations related to special unloading of goods/consignment/equipment .";
                dict.Add("137", new TransportationStatusRecord("137", "Disembarking passengers"));
                dict["137"].description = "The disembarkation of passengers.";
                dict.Add("138", new TransportationStatusRecord("138", "Relocation of a means of transport"));
                dict["138"].description = "Relocating of a means of transport.";
                dict.Add("139", new TransportationStatusRecord("139", "Manoeuvring operations, entering port"));
                dict["139"].description = "Manoeuvring operations connected with entering the port .";
                dict.Add("140", new TransportationStatusRecord("140", "Manoeuvring operations, leaving port"));
                dict["140"].description = "Manoeuvring operations connected with leaving the port .";
                dict.Add("141", new TransportationStatusRecord("141", "Manoeuvring operations, within the port"));
                dict["141"].description = "Manoeuvring operations connected with movement within the port .";
                dict.Add("142", new TransportationStatusRecord("142", "Means of transport, under preparation"));
                dict["142"].description = "Preparation for handling of the means of transport.";
                dict.Add("143", new TransportationStatusRecord("143", "Ballast loading"));
                dict["143"].description = "Loading of ballast.";
                dict.Add("144", new TransportationStatusRecord("144", "Ballast unloading"));
                dict["144"].description = "Unloading of ballast.";
                dict.Add("145", new TransportationStatusRecord("145", "Cargo space under preparation"));
                dict["145"].description = "Preparation of the cargo space of the means of transport.";
                dict.Add("146", new TransportationStatusRecord("146", "Provisioning"));
                dict["146"].description = "Provision of supplies for a means of transport.";
                dict.Add("147", new TransportationStatusRecord("147", "Provisioning, fuel"));
                dict["147"].description = "Provision of fuel for a means of transport.";
                dict.Add("148", new TransportationStatusRecord("148", "Provisioning, water"));
                dict["148"].description = "Provision of water for a means of transport.";
                dict.Add("149", new TransportationStatusRecord("149", "Provisioning, oil"));
                dict["149"].description = "Provision of oil for a means of transport.";
                dict.Add("150", new TransportationStatusRecord("150", "Provisioning, food"));
                dict["150"].description = "Provision of food  for a means of transport.";
                dict.Add("151", new TransportationStatusRecord("151", "Sanitary operations"));
                dict["151"].description = "Operations related to sanitary conditions.";
                dict.Add("152", new TransportationStatusRecord("152", "Fumigation operations"));
                dict["152"].description = "Operations related to fumigation of the equipment or the means of transport.";
                dict.Add("153", new TransportationStatusRecord("153", "Disinfestation operations"));
                dict["153"].description = "Operations related to disinfestation of the equipment or the means of transport.";
                dict.Add("154", new TransportationStatusRecord("154", "Deratization operations"));
                dict["154"].description = "Operations related to deratization of the means of transport.";
                dict.Add("155", new TransportationStatusRecord("155", "Degasation operations"));
                dict["155"].description = "Operations related to the removal of unwanted gas.";
                dict.Add("156", new TransportationStatusRecord("156", "Crew recruitment operation"));
                dict["156"].description = "Operation related to recruitment of crew .";
                dict.Add("157", new TransportationStatusRecord("157", "Training operations"));
                dict["157"].description = "Operations related to training.";
                dict.Add("158", new TransportationStatusRecord("158", "Salvage operations"));
                dict["158"].description = "Operations related to salvage work.";
                dict.Add("159", new TransportationStatusRecord("159", "Loading, alongside"));
                dict["159"].description = "Loading the goods  when the means of transport is alongside.";
                dict.Add("161", new TransportationStatusRecord("161", "Loading, at anchor"));
                dict["161"].description = "Loading the goods  when the means of transport is at anchor.";
                dict.Add("162", new TransportationStatusRecord("162", "Unloading, at wharf"));
                dict["162"].description = "Unloading the goods  when the means of transport is at the wharf.";
                dict.Add("163", new TransportationStatusRecord("163", "Unloading on board"));
                dict["163"].description = "Unloading the goods from the vessel .";
                dict.Add("164", new TransportationStatusRecord("164", "Unloading, at anchor"));
                dict["164"].description = "Unloading the goods  when the means of transport is at anchor.";
                dict.Add("165", new TransportationStatusRecord("165", "Loading and unloading, simultaneously"));
                dict["165"].description = "Loading and unloading operations simultaneously.";
                dict.Add("166", new TransportationStatusRecord("166", "Idle time operations"));
                dict["166"].description = "Operations during idle time pending a scheduled event.";
                dict.Add("167", new TransportationStatusRecord("167", "Technical operations"));
                dict["167"].description = "Operations of a technical nature.";
                dict.Add("168", new TransportationStatusRecord("168", "Compass calibration"));
                dict["168"].description = "Operations related to calibration of a compass.";
                dict.Add("169", new TransportationStatusRecord("169", "Document, clearance operation"));
                dict["169"].description = "Operation related to clearance of a document.";
                dict.Add("170", new TransportationStatusRecord("170", "Customs formalities operation"));
                dict["170"].description = "Operation related to customs formalities.";
                dict.Add("171", new TransportationStatusRecord("171", "Medical control operations"));
                dict["171"].description = "Medical control operations related to the crew.";
                dict.Add("172", new TransportationStatusRecord("172", "Loading, preparation for"));
                dict["172"].description = "Preparation for the loading of the goods.";
                dict.Add("174", new TransportationStatusRecord("174", "Unloading, preparation for"));
                dict["174"].description = "Preparation for the unloading of the goods.";
                dict.Add("175", new TransportationStatusRecord("175", "Unloading, polluted ballast"));
                dict["175"].description = "Unloading of polluted ballast.";
                dict.Add("176", new TransportationStatusRecord("176", "Obtaining documents from shipping register"));
                dict["176"].description = "Operations related to obtaining documents from the  shipping register.";
                dict.Add("177", new TransportationStatusRecord("177", "Obtaining wreckage documentation"));
                dict["177"].description = "Operations related to obtaining documents for a wrecked means of transport.";
                dict.Add("178", new TransportationStatusRecord("178", "Waiting, to enter or leave"));
                dict["178"].description = "Waiting to enter or leave.";
                dict.Add("179", new TransportationStatusRecord("179", "Waiting, for a pilot"));
                dict["179"].description = "Waiting for an available pilot.";
                dict.Add("180", new TransportationStatusRecord("180", "Waiting, for a tug"));
                dict["180"].description = "Waiting for an available tug.";
                dict.Add("181", new TransportationStatusRecord("181", "Waiting, for day light"));
                dict["181"].description = "Waiting for day light hours.";
                dict.Add("182", new TransportationStatusRecord("182", "Waiting, due to meteorological circumstances"));
                dict["182"].description = "Waiting due to meteorological circumstances.";
                dict.Add("183", new TransportationStatusRecord("183", "Waiting, to form a convoy"));
                dict["183"].description = "Waiting to form a convoy.";
                dict.Add("184", new TransportationStatusRecord("184", "Waiting, for action by authorities"));
                dict["184"].description = "Waiting for  action to be taken by authorities.";
                dict.Add("185", new TransportationStatusRecord("185", "Waiting, due to a ban"));
                dict["185"].description = "Waiting due to a ban.";
                dict.Add("186", new TransportationStatusRecord("186", "Waiting, for entry permission"));
                dict["186"].description = "Waiting for entry permission from the authorities.";
                dict.Add("187", new TransportationStatusRecord("187", "Waiting, due to an action taken by authorities"));
                dict["187"].description = "Waiting due to an action taken by the authorities";
                dict.Add("188", new TransportationStatusRecord("188", "Waiting, due to the terms of charter"));
                dict["188"].description = "Waiting due to terms of  the charter.";
                dict.Add("189", new TransportationStatusRecord("189", "Waiting, for a location"));
                dict["189"].description = "Waiting for a location .";
                dict.Add("190", new TransportationStatusRecord("190", "Waiting, for cargo"));
                dict["190"].description = "Waiting for cargo.";
                dict.Add("191", new TransportationStatusRecord("191", "Waiting, for workers"));
                dict["191"].description = "Waiting for workers.";
                dict.Add("192", new TransportationStatusRecord("192", "Waiting, for storage area"));
                dict["192"].description = "Waiting for a storage area.";
                dict.Add("193", new TransportationStatusRecord("193", "Waiting, for equipment"));
                dict["193"].description = "Waiting for equipment.";
                dict.Add("194", new TransportationStatusRecord("194", "Waiting, for other means of transport"));
                dict["194"].description = "Waiting for other means of transport.";
                dict.Add("195", new TransportationStatusRecord("195", "Waiting, for handling equipment"));
                dict["195"].description = "Waiting for handling equipment.";
                dict.Add("196", new TransportationStatusRecord("196", "Waiting, for on board handling equipment"));
                dict["196"].description = "Waiting for onboard handling equipment.";
                dict.Add("197", new TransportationStatusRecord("197", "Waiting, for cargo to be ready for loading"));
                dict["197"].description = "Waiting due to the cargo not being ready to be loaded/handled.";
                dict.Add("198", new TransportationStatusRecord("198", "Waiting, for means of transport to be  ready"));
                dict["198"].description = "Waiting due to the means of transport not being ready.";
                dict.Add("199", new TransportationStatusRecord("199", "Waiting, due to damaged cargo"));
                dict["199"].description = "Waiting because cargo was damaged.";
                dict.Add("200", new TransportationStatusRecord("200", "Waiting, for operational periods"));
                dict["200"].description = "Waiting due to being outside the period of operation.";
                dict.Add("201", new TransportationStatusRecord("201", "Waiting, for repair and/or maintenance of the means of transport"));
                dict["201"].description = "Waiting due to repairs and/or maintenance to the means of transport.";
                dict.Add("202", new TransportationStatusRecord("202", "Waiting, for repair and/or maintenance of handling equipment"));
                dict["202"].description = "Waiting due to repairs and/or maintenance of handling equipment.";
                dict.Add("203", new TransportationStatusRecord("203", "Embarking passengers from tender"));
                dict["203"].description = "The embarkation of passengers from a tender.";
                dict.Add("204", new TransportationStatusRecord("204", "Waiting, for a counter convoy to pass"));
                dict["204"].description = "Waiting due to passage of counter  convoy.";
                dict.Add("205", new TransportationStatusRecord("205", "Delivery address outside delivery area"));
                dict["205"].description = "The address for delivery is outside the area of the carrier/transport operator.";
                dict.Add("206", new TransportationStatusRecord("206", "Arrival, after means of transport departed"));
                dict["206"].description = "The goods/consignment/equipment has arrived after the means of transport has depa" +
                    "rted.";
                dict.Add("207", new TransportationStatusRecord("207", "Delivery refused, agent"));
                dict["207"].description = "The agent  refused to accept delivery.";
                dict.Add("208", new TransportationStatusRecord("208", "Seals, replaced"));
                dict["208"].description = "The seals on the equipment have been replaced.";
                dict.Add("209", new TransportationStatusRecord("209", "Delivery, scheduled"));
                dict["209"].description = "The delivery has been scheduled.";
                dict.Add("210", new TransportationStatusRecord("210", "Delivery, unsuccessful attempt"));
                dict["210"].description = "An unsuccessful attempt has been made to deliver the goods/consignment/equipment." +
                    "";
                dict.Add("211", new TransportationStatusRecord("211", "Delivery not completed, business closed"));
                dict["211"].description = "The goods/consignment/equipment could not be delivered as the business was closed" +
                    ".";
                dict.Add("212", new TransportationStatusRecord("212", "Delivery, changed schedule"));
                dict["212"].description = "The goods/consignment/equipment cannot be delivered at the arranged time because " +
                    "of a change of schedule.";
                dict.Add("213", new TransportationStatusRecord("213", "Delivery, further address needed"));
                dict["213"].description = "A further address is needed to effect delivery of the goods/consignment/ equipmen" +
                    "t.";
                dict.Add("214", new TransportationStatusRecord("214", "Computer system not in operation"));
                dict["214"].description = "The computer system is not in operation.";
                dict.Add("215", new TransportationStatusRecord("215", "Delivery, awaiting credit approval"));
                dict["215"].description = "Delivery on a credit base is requested.";
                dict.Add("216", new TransportationStatusRecord("216", "Delivery, awaiting customer arrangements"));
                dict["216"].description = "The goods/consignment/equipment require delivery arrangements by the customer.";
                dict.Add("218", new TransportationStatusRecord("218", "Damaged"));
                dict["218"].description = "The goods/consignments/equipment have been damaged.";
                dict.Add("219", new TransportationStatusRecord("219", "Delivery pending, awaiting specified dates/times/periods"));
                dict["219"].description = "Delivery of the goods/consignment/equipment is pending awaiting specified dates/t" +
                    "imes/periods.";
                dict.Add("220", new TransportationStatusRecord("220", "Destination incorrect"));
                dict["220"].description = "The goods/consignment/equipment has been sent to an incorrect  destination.";
                dict.Add("222", new TransportationStatusRecord("222", "Derailment"));
                dict["222"].description = "The train has derailed.";
                dict.Add("224", new TransportationStatusRecord("224", "Delivery, industrial dispute"));
                dict["224"].description = "The goods/consignment/equipment cannot be delivered due to an industrial dispute." +
                    "";
                dict.Add("225", new TransportationStatusRecord("225", "Operation affected by customer action"));
                dict["225"].description = "An operation has been affected by an action of the customer.";
                dict.Add("227", new TransportationStatusRecord("227", "Delivery, equipment failure"));
                dict["227"].description = "The goods/consignment/equipment cannot be delivered due to a failure in the equip" +
                    "ment.";
                dict.Add("228", new TransportationStatusRecord("228", "Inspection required by authority"));
                dict["228"].description = "An inspection of the goods/equipment is required  by an authority.";
                dict.Add("229", new TransportationStatusRecord("229", "Export suspended"));
                dict["229"].description = "The goods/consignment/equipment has been suspended from export pending further in" +
                    "vestigation.";
                dict.Add("231", new TransportationStatusRecord("231", "Missing, goods item"));
                dict["231"].description = "The goods item is missing.";
                dict.Add("232", new TransportationStatusRecord("232", "Import suspended"));
                dict["232"].description = "The goods/consignment/equipment has been suspended from import pending further in" +
                    "vestigation.";
                dict.Add("233", new TransportationStatusRecord("233", "Incorrect picklist"));
                dict["233"].description = "The goods/consignment/equipment was not collected/picked-up due to an incorrect p" +
                    "icklist.";
                dict.Add("234", new TransportationStatusRecord("234", "Incorrect address"));
                dict["234"].description = "The address is incorrect.";
                dict.Add("235", new TransportationStatusRecord("235", "Industrial dispute"));
                dict["235"].description = "An industrial dispute has happened.";
                dict.Add("236", new TransportationStatusRecord("236", "Waiting, for instructions"));
                dict["236"].description = "Waiting for further instructions.";
                dict.Add("238", new TransportationStatusRecord("238", "Means of transport, damaged"));
                dict["238"].description = "The means of transport  has been damaged.";
                dict.Add("239", new TransportationStatusRecord("239", "Mechanical breakdown"));
                dict["239"].description = "There has been a mechanical breakdown of the means of transport/equipment .";
                dict.Add("240", new TransportationStatusRecord("240", "Mechanical inspection required"));
                dict["240"].description = "A mechanical inspection of the means of transport/equipment  is required.";
                dict.Add("241", new TransportationStatusRecord("241", "Missing, document"));
                dict["241"].description = "The document for the goods/consignments/equipment is missing.";
                dict.Add("242", new TransportationStatusRecord("242", "New delivery arrangements advised"));
                dict["242"].description = "New  delivery arrangements have been advised .";
                dict.Add("243", new TransportationStatusRecord("243", "No recipient contact information"));
                dict["243"].description = "No contact information available concerning the recipient. .";
                dict.Add("247", new TransportationStatusRecord("247", "Collection/pick-up, package not available"));
                dict["247"].description = "The package is not available for collection/pick-up.";
                dict.Add("248", new TransportationStatusRecord("248", "Tracking number unknown"));
                dict["248"].description = "The tracking number of the goods/consignment/equipment is unknown.";
                dict.Add("250", new TransportationStatusRecord("250", "Transport payment not received"));
                dict["250"].description = "The transport payment  has not been received.";
                dict.Add("251", new TransportationStatusRecord("251", "Refused, non-payment by payer"));
                dict["251"].description = "Payer refused to make the payment.";
                dict.Add("253", new TransportationStatusRecord("253", "Refused, no reason given"));
                dict["253"].description = "The transport action/documentation has been refused without a reason given.";
                dict.Add("254", new TransportationStatusRecord("254", "Delivery, scheduled past cut-off time"));
                dict["254"].description = "The goods/consignment/equipment to be delivered has been scheduled past the cut-o" +
                    "ff time.";
                dict.Add("255", new TransportationStatusRecord("255", "Shunted to siding"));
                dict["255"].description = "The means of transport  has been shunted to a siding.";
                dict.Add("256", new TransportationStatusRecord("256", "Signature not required"));
                dict["256"].description = "A signature is not required.";
                dict.Add("258", new TransportationStatusRecord("258", "Special service required"));
                dict["258"].description = "A special service is required.";
                dict.Add("260", new TransportationStatusRecord("260", "Tracking information unavailable"));
                dict["260"].description = "The tracking information is unavailable.";
                dict.Add("265", new TransportationStatusRecord("265", "Reason unknown"));
                dict["265"].description = "The reason is unknown.";
                dict.Add("266", new TransportationStatusRecord("266", "Delivery delayed, adverse weather conditions"));
                dict["266"].description = "Adverse weather conditions have delayed delivery.";
                dict.Add("267", new TransportationStatusRecord("267", "Free storage time expired"));
                dict["267"].description = "The goods/consignment/equipment has been in a storage facility for longer than th" +
                    "e permitted free time.";
                dict.Add("269", new TransportationStatusRecord("269", "Delivery, consignee absent"));
                dict["269"].description = "The goods/consignment/equipment cannot be delivered as the consignee  was absent." +
                    "";
                dict.Add("270", new TransportationStatusRecord("270", "Delayed operation, local circumstances"));
                dict["270"].description = "The operation is  delayed due to local circumstances.";
                dict.Add("271", new TransportationStatusRecord("271", "Delayed operation, consignee\'s instructions"));
                dict["271"].description = "The operation is  delayed awaiting consignee\'s instructions.";
                dict.Add("272", new TransportationStatusRecord("272", "Delayed operation, consignor\'s instructions"));
                dict["272"].description = "The operation is  delayed awaiting consignor\'s instructions.";
                dict.Add("273", new TransportationStatusRecord("273", "Delayed operation"));
                dict["273"].description = "The operation is delayed.";
                dict.Add("274", new TransportationStatusRecord("274", "Incomplete address"));
                dict["274"].description = "The address is incomplete.";
                dict.Add("275", new TransportationStatusRecord("275", "Delivery refused, purchase order cancelled"));
                dict["275"].description = "The delivery was refused as the purchase order has been cancelled.";
                dict.Add("276", new TransportationStatusRecord("276", "Delivery refused, return to the consignor"));
                dict["276"].description = "The delivery was refused and the goods/consignment/equipment will be returned to " +
                    "the consignor .";
                dict.Add("277", new TransportationStatusRecord("277", "Delivery refused, inconsistent with purchase order"));
                dict["277"].description = "The delivery was refused as an inconsistency with the purchase order was found.";
                dict.Add("278", new TransportationStatusRecord("278", "Delivery refused, incorrect delivery date"));
                dict["278"].description = "The delivery was refused as the delivery date was incorrect.";
                dict.Add("279", new TransportationStatusRecord("279", "Delivery refused, automatic return"));
                dict["279"].description = "The delivery was refused and the goods/consignment/equipment is automatically ret" +
                    "urned as instructed.";
                dict.Add("280", new TransportationStatusRecord("280", "Delivery refused, duplicate delivery"));
                dict["280"].description = "The delivery was refused because of duplicate delivery.";
                dict.Add("281", new TransportationStatusRecord("281", "Delivery refused, instructions requested"));
                dict["281"].description = "The delivery was refused and instructions are requested.";
                dict.Add("282", new TransportationStatusRecord("282", "Delivery refused, consignee\'s condition"));
                dict["282"].description = "The delivery was refused due to the consignee\'s condition.";
                dict.Add("283", new TransportationStatusRecord("283", "Delivery refused, delivery incomplete"));
                dict["283"].description = "The delivery was refused due to incomplete delivery.";
                dict.Add("284", new TransportationStatusRecord("284", "Delivery refused, not ordered"));
                dict["284"].description = "The delivery was refused as the goods/consignment/equipment had not been ordered " +
                    ".";
                dict.Add("285", new TransportationStatusRecord("285", "Delivery refused, remainder not accepted"));
                dict["285"].description = "The delivery of the remaining goods was not accepted.";
                dict.Add("286", new TransportationStatusRecord("286", "Delivery refused, spoilt state"));
                dict["286"].description = "The delivery was refused as the goods/consignment/equipment was in a spoilt state" +
                    ".";
                dict.Add("287", new TransportationStatusRecord("287", "Missing, contents"));
                dict["287"].description = "The contents are missing.";
                dict.Add("288", new TransportationStatusRecord("288", "Not on package list"));
                dict["288"].description = "The goods/consignment is not on the package list";
                dict.Add("291", new TransportationStatusRecord("291", "Delivery refused, collect freight charges not paid"));
                dict["291"].description = "The delivery was refused as the collect freight charge were not paid.";
                dict.Add("292", new TransportationStatusRecord("292", "Delivery refused, reimbursement not paid"));
                dict["292"].description = "The delivery was refused as the reimbursement was not paid.";
                dict.Add("295", new TransportationStatusRecord("295", "Delivery refused, opened"));
                dict["295"].description = "The delivery was refused as the goods/consignment was found to be opened.";
                dict.Add("297", new TransportationStatusRecord("297", "Delivery refused, commercial dispute"));
                dict["297"].description = "The delivery was refused because of a commercial dispute.";
                dict.Add("298", new TransportationStatusRecord("298", "Delivery refused, error on product or packaging"));
                dict["298"].description = "The delivery was refused as an error was found on  product or packaging.";
                dict.Add("299", new TransportationStatusRecord("299", "Delivery refused, delivery date/time changed"));
                dict["299"].description = "The delivery was refused as the delivery date or time has been changed.";
                dict.Add("300", new TransportationStatusRecord("300", "Document, received without goods"));
                dict["300"].description = "A document for a consignment has been received without the corresponding goods.";
                dict.Add("301", new TransportationStatusRecord("301", "Goods, received without documentation"));
                dict["301"].description = "Goods/consignment has been received without the corresponding  documentation.";
                dict.Add("302", new TransportationStatusRecord("302", "Overcarried consignment"));
                dict["302"].description = "The consignment has been overcarried.";
                dict.Add("306", new TransportationStatusRecord("306", "Document, found"));
                dict["306"].description = "The document has been found.";
                dict.Add("307", new TransportationStatusRecord("307", "Damaged but deliverable"));
                dict["307"].description = "The goods/consignment/equipment has been damaged but delivery can be completed.";
                dict.Add("308", new TransportationStatusRecord("308", "Spoilt"));
                dict["308"].description = "The goods/consignment/equipment is spoilt.";
                dict.Add("309", new TransportationStatusRecord("309", "Packaging/equipment opened"));
                dict["309"].description = "The packaging/equipment has been opened.";
                dict.Add("310", new TransportationStatusRecord("310", "Processed as contractually agreed"));
                dict["310"].description = "The goods/consignment/equipment has been processed as contractually agreed.";
                dict.Add("311", new TransportationStatusRecord("311", "Claim folder opened"));
                dict["311"].description = "A claim folder has been opened .";
                dict.Add("312", new TransportationStatusRecord("312", "Moved, completed"));
                dict["312"].description = "The goods/consignment/equipment has been moved.";
                dict.Add("313", new TransportationStatusRecord("313", "Returned by recipient"));
                dict["313"].description = "The goods/consignment/equipment has been returned by the recipient.";
                dict.Add("314", new TransportationStatusRecord("314", "Delayed, at origin"));
                dict["314"].description = "The goods/consignment/equipment/means of transport has been delayed at the origin" +
                    ".";
                dict.Add("315", new TransportationStatusRecord("315", "Held, by logistic service provider"));
                dict["315"].description = "The goods/consignment/equipment has been held by the logistic service provider.";
                dict.Add("316", new TransportationStatusRecord("316", "Incident occurred but accepted by ordering party"));
                dict["316"].description = "An incident has occurred but has been accepted by the ordering party.";
                dict.Add("317", new TransportationStatusRecord("317", "Delivery party\' premises closed during normal hours"));
                dict["317"].description = "The premises of the delivery party were closed during normal hours.";
                dict.Add("318", new TransportationStatusRecord("318", "Delivery incomplete, time shortage"));
                dict["318"].description = "The delivery of the goods/consignment/equipment could not be completed due to a s" +
                    "hortage of time to handle the delivery.";
                dict.Add("319", new TransportationStatusRecord("319", "Despatch, preparation error"));
                dict["319"].description = "An error occurred during the preparation of the despatch.";
                dict.Add("320", new TransportationStatusRecord("320", "Undefined incident attributed to logistic server provider"));
                dict["320"].description = "An undefined incident has occurred which has been attributed to the logistic serv" +
                    "ice provider.";
                dict.Add("321", new TransportationStatusRecord("321", "Instruction to despatch, received"));
                dict.Add("322", new TransportationStatusRecord("322", "Despatch, under preparation"));
                dict["322"].description = "The despatch of the goods/consignment/equipment is in preparation.";
                dict.Add("323", new TransportationStatusRecord("323", "Return in progress"));
                dict["323"].description = "The goods/consignment/equipment is being returned.";
                dict.Add("324", new TransportationStatusRecord("324", "Instruction to despatch, cancelled"));
                dict["324"].description = "The instruction to despatch has been cancelled.";
                dict.Add("325", new TransportationStatusRecord("325", "Delivery refused, by recipient"));
                dict["325"].description = "The delivery of the goods/consignment/equipment has been refused by the recipient" +
                    ".";
                dict.Add("326", new TransportationStatusRecord("326", "Goods, held by third party on instruction from owner"));
                dict["326"].description = "Goods are held under control of a third party following an instruction from the o" +
                    "wner of the goods.";
                dict.Add("327", new TransportationStatusRecord("327", "Weight or volume loss"));
                dict["327"].description = "The goods have suffered a weight or volume loss.";
                dict.Add("328", new TransportationStatusRecord("328", "Moved, internally"));
                dict["328"].description = "The goods/consignment/equipment has been moved internally.";
                dict.Add("329", new TransportationStatusRecord("329", "Consignment partially stolen"));
                dict["329"].description = "The consignment has been partially stolen.";
                dict.Add("330", new TransportationStatusRecord("330", "Consignment partially lost or missing"));
                dict["330"].description = "The consignment is partially lost or missing.";
                dict.Add("331", new TransportationStatusRecord("331", "Destroyed"));
                dict["331"].description = "The goods/consignment/equipment has been destroyed.";
                dict.Add("332", new TransportationStatusRecord("332", "Action by logistics service provider"));
                dict["332"].description = "An action was taken by the logistics service provider.";
                dict.Add("333", new TransportationStatusRecord("333", "Action by logistics service provider on instruction by owner"));
                dict["333"].description = "An action  was taken by the logistics service provider as instructed by owner of " +
                    "the goods.";
                dict.Add("334", new TransportationStatusRecord("334", "Document, refused"));
                dict["334"].description = "The document has been refused.";
                dict.Add("335", new TransportationStatusRecord("335", "Seals, damaged"));
                dict["335"].description = "The seals on the equipment have been damaged.";
                dict.Add("336", new TransportationStatusRecord("336", "Seals, broken"));
                dict["336"].description = "The seals on the equipment have been broken.";
                dict.Add("337", new TransportationStatusRecord("337", "Seals, tampered"));
                dict["337"].description = "The seals on the equipment have been tampered.";
                dict.Add("338", new TransportationStatusRecord("338", "Collection/pick-up, business closed"));
                dict["338"].description = "The goods/consignment/equipment could not be collected/picked-up as the business " +
                    "was closed.";
                dict.Add("339", new TransportationStatusRecord("339", "Collection/pick-up, changed schedule"));
                dict["339"].description = "The goods/consignment/equipment cannot be collected/picked-up at the arranged tim" +
                    "e because of a change of schedule.";
                dict.Add("340", new TransportationStatusRecord("340", "Collection/pick-up, further address needed"));
                dict["340"].description = "A further address is needed to effect collection/pick-up of the goods/consignment" +
                    "/ equipment.";
                dict.Add("341", new TransportationStatusRecord("341", "Collection/pick-up, industrial dispute"));
                dict["341"].description = "The goods/consignment/equipment cannot be collected/picked-up due to an industria" +
                    "l dispute.";
                dict.Add("342", new TransportationStatusRecord("342", "Collection/pick-up, equipment failure"));
                dict["342"].description = "The goods/consignment/equipment cannot be collected/picked-up due to a failure in" +
                    " the equipment.";
                dict.Add("343", new TransportationStatusRecord("343", "Document, incorrect"));
                dict["343"].description = "The document for the goods/consignments/equipment is incorrect.";
                dict.Add("344", new TransportationStatusRecord("344", "Collection/pick-up, scheduled past cut-off time"));
                dict["344"].description = "The goods/consignment/equipment to be collected/picked-up has been scheduled past" +
                    " the cut-off time.";
                dict.Add("345", new TransportationStatusRecord("345", "Collection/pick-up, adverse weather conditions"));
                dict["345"].description = "Adverse weather conditions have affected collection/pick-up.";
                dict.Add("346", new TransportationStatusRecord("346", "Unloading, completed from a means of transport"));
                dict["346"].description = "The goods/consignment/equipment has been unloaded from a means of transport.";
                dict.Add("347", new TransportationStatusRecord("347", "Deliverable"));
                dict["347"].description = "The goods/consignment/equipment can be delivered.";
                dict.Add("348", new TransportationStatusRecord("348", "Not deliverable"));
                dict["348"].description = "The goods/consignment/equipment cannot be delivered.";
                dict.Add("349", new TransportationStatusRecord("349", "Handed over"));
                dict["349"].description = "The goods/consignment/equipment has been handed over to another party.";
                dict.Add("350", new TransportationStatusRecord("350", "Signature required"));
                dict["350"].description = "A signature is required.";
                dict.Add("351", new TransportationStatusRecord("351", "Defined incident attributed to logistic server provider"));
                dict["351"].description = "A defined incident has occurred which has been attributed to the logistic service" +
                    " provider.";
                dict.Add("352", new TransportationStatusRecord("352", "Delivery not completed, business closed, inventory count"));
                dict["352"].description = "The goods/consignment/equipment could not be delivered as the business was closed" +
                    " due to inventory count.";
                dict.Add("353", new TransportationStatusRecord("353", "Delivery not completed, business closed on Saturday"));
                dict["353"].description = "The goods/consignment/equipment could not be delivered as the business was closed" +
                    " on Saturday.";
                dict.Add("354", new TransportationStatusRecord("354", "Delivery not completed, business closed on national holiday"));
                dict["354"].description = "The goods/consignment/equipment could not be delivered as the business was closed" +
                    " on a national holiday.";
                dict.Add("355", new TransportationStatusRecord("355", "En route, via local route"));
                dict["355"].description = "The goods/consignment/equipment/means of transport is moving to destination via a" +
                    " local route.";
                dict.Add("356", new TransportationStatusRecord("356", "En route, via national route"));
                dict["356"].description = "The goods/consignment/equipment/means of transport is moving to destination via a" +
                    " national route.";
                dict.Add("357", new TransportationStatusRecord("357", "En route, via international route"));
                dict["357"].description = "The goods/consignment/equipment/means of transport is moving to destination via a" +
                    "n international route.";
                dict.Add("358", new TransportationStatusRecord("358", "Transport terminated, mail not received"));
                dict["358"].description = "The transport of the goods/consignment/equipment/means of transport has been term" +
                    "inated and the mail has not been received.";
                dict.Add("359", new TransportationStatusRecord("359", "Bill of Lading issued"));
                dict["359"].description = "The Bill of Lading for the goods/consignment/equipment has been issued.";
                dict.Add("360", new TransportationStatusRecord("360", "Cleared, by logistics service provider"));
                dict["360"].description = "The goods/consignment/equipment/means of transport has been cleared by logistics " +
                    "service provider.";
                dict.Add("361", new TransportationStatusRecord("361", "Delivery, expected"));
                dict["361"].description = "The goods/consignment/equipment expected to be delivered.";
                dict.Add("362", new TransportationStatusRecord("362", "Measured"));
                dict["362"].description = "The goods/consignment/equipment/means of transport has been measured.";
                dict.Add("363", new TransportationStatusRecord("363", "Loading, ready"));
                dict["363"].description = "The goods/consignment/equipment is ready to be loaded onto a means of transport.";
                dict.Add("364", new TransportationStatusRecord("364", "Arrival, at yard"));
                dict["364"].description = "The goods/consignment/equipment/means of transport has arrived at the yard.";
                dict.Add("365", new TransportationStatusRecord("365", "Departure, from yard"));
                dict["365"].description = "The goods/consignment/equipment/means of transport has departed from the yard.";
                dict.Add("366", new TransportationStatusRecord("366", "Accepted at interchange point"));
                dict["366"].description = "The goods/consignment/equipment/means of transport has been accepted at the inter" +
                    "change point.";
                dict.Add("367", new TransportationStatusRecord("367", "Alerted, no action taken"));
                dict["367"].description = "No action taken after an alert in relation to the goods/consignment/equipment/mea" +
                    "ns of transport.";
                dict.Add("368", new TransportationStatusRecord("368", "Transshipment to another wagon"));
                dict["368"].description = "The goods/consignment has been transhipped to another wagon.";
                dict.Add("369", new TransportationStatusRecord("369", "Trip plan revised manually"));
                dict["369"].description = "The transport route has been re-programmed manually.";
                dict.Add("370", new TransportationStatusRecord("370", "Special wagon handling arranged"));
                dict["370"].description = "The handling of a special wagon has been arranged.";
                return dict;
            }
        }
        
        public ITela.CodeValueCollection ToCodeValueCollection()
        {
            var collection = new ITela.CodeValueCollection();
            var data = DATA.Values.ToArray();
            for (int i = 0; (i < data.Length); i = (i + 1))
            {
                collection.Add(data[i].Code, data[i].Value);
            }
            return collection;
        }
        
        public static IEnumerable<string> GetCodesAll()
        {
            return DATA.Keys;
        }
        
        public static IEnumerable<string> GetCodesAllNotIn<T>()
            where T : struct
        {
            var fields = System.Enum.GetValues(typeof(T));
            if ((fields.Length == 0))
            {
                throw new System.ArgumentOutOfRangeException("fields", "Enum of type T must contain at least one field.");
            }
            var existingCodes = new List<string>();
            for (int i = 0; (i < fields.Length); i = (i + 1))
            {
                var code = GcCodeValueParser.ReadCode(((System.Enum)(fields.GetValue(i))));
                existingCodes.Add(code);
            }
            return DATA.Keys.Except(existingCodes);
        }
        
        public static string GetValue(string code)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 3))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 3 or less characters.");
            }
            return DATA[code].Value;
        }
        
        public static string GetValue(string code, Func<TransportationStatusRecord, string> selector)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 3))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 3 or less characters.");
            }
            return selector(DATA[code]);
        }
        
        public static decimal GetValue(string code, Func<TransportationStatusRecord, decimal> selector)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 3))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 3 or less characters.");
            }
            return selector(DATA[code]);
        }
        
        public static int GetValue(string code, Func<TransportationStatusRecord, int> selector)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 3))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 3 or less characters.");
            }
            return selector(DATA[code]);
        }
        
        /// <summary>
        /// Returns a list of codes with data in selected column that match search text.
        /// Exact matches (equality ignoring cases) are returned first,
        /// then partial matches (always ignoring cases) if forceExactMatch has not been set.
        /// </summary>
        public static IEnumerable<string> GetCodesLike(string text, Func<TransportationStatusRecord, string> selector, bool forceExactMatch)
        {
            if ((text == null))
            {
                throw new System.ArgumentNullException("text");
            }
            var exactMatchingCodes = DATA.Where(x => selector(x.Value) != null && selector(x.Value).ToLowerInvariant() == text.ToLowerInvariant()).Select(x => x.Key);
            if ((forceExactMatch == true))
            {
                return exactMatchingCodes;
            }
            var containMatchingCodes = DATA.Where(x => selector(x.Value) != null && text.ToLowerInvariant().Contains(selector(x.Value).ToLowerInvariant())).Select(x => x.Key);
            var codes = new List<string>();
            codes.AddRange(exactMatchingCodes);
            codes.AddRange(containMatchingCodes.Except(exactMatchingCodes));
            return codes;
        }
    }
}
