//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITela.Gc
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    /// <summary>
    /// 
    /// </summary>
    public class PackagingType
    {
        
        private static Dictionary<string, PackagingTypeRecord> _data;
        
        public static Dictionary<string, PackagingTypeRecord> DATA
        {
            get
            {
                if ((_data == null))
                {
                    _data = new Dictionary<string, PackagingTypeRecord>();
                    _data.Add("1A", new PackagingTypeRecord("1A", "Drum, steel"));
                    _data["1A"].numeric = "34";
                    _data.Add("1B", new PackagingTypeRecord("1B", "Drum, aluminium"));
                    _data["1B"].numeric = "34";
                    _data.Add("1D", new PackagingTypeRecord("1D", "Drum, plywood"));
                    _data["1D"].numeric = "34";
                    _data.Add("1F", new PackagingTypeRecord("1F", "Container, flexible"));
                    _data["1F"].description = "A packaging container of flexible construction.";
                    _data["1F"].numeric = "93";
                    _data.Add("1G", new PackagingTypeRecord("1G", "Drum, fibre"));
                    _data["1G"].numeric = "34";
                    _data.Add("1W", new PackagingTypeRecord("1W", "Drum, wooden"));
                    _data["1W"].numeric = "34 or 35";
                    _data.Add("2C", new PackagingTypeRecord("2C", "Barrel, wooden"));
                    _data["2C"].numeric = "44 or 45";
                    _data.Add("3A", new PackagingTypeRecord("3A", "Jerrican, steel"));
                    _data["3A"].numeric = "23 or 33";
                    _data.Add("3H", new PackagingTypeRecord("3H", "Jerrican, plastic"));
                    _data["3H"].numeric = "23 or 33";
                    _data.Add("43", new PackagingTypeRecord("43", "Bag, super bulk"));
                    _data["43"].description = "A cloth plastic or paper based bag having the dimensions of the pallet on which i" +
                        "t is constructed.";
                    _data["43"].numeric = "64";
                    _data.Add("44", new PackagingTypeRecord("44", "Bag, polybag"));
                    _data["44"].description = "A type of plastic bag, typically used to wrap promotional pieces, publications, p" +
                        "roduct samples, and/or catalogues.";
                    _data["44"].numeric = "62 or 63";
                    _data.Add("4A", new PackagingTypeRecord("4A", "Box, steel"));
                    _data["4A"].numeric = "21 to 25";
                    _data.Add("4B", new PackagingTypeRecord("4B", "Box, aluminium"));
                    _data["4B"].numeric = "21 to 25";
                    _data.Add("4C", new PackagingTypeRecord("4C", "Box, natural wood"));
                    _data["4C"].numeric = "21 to 25";
                    _data.Add("4D", new PackagingTypeRecord("4D", "Box, plywood"));
                    _data["4D"].numeric = "21 to 25";
                    _data.Add("4F", new PackagingTypeRecord("4F", "Box, reconstituted wood"));
                    _data["4F"].numeric = "21 to 25";
                    _data.Add("4G", new PackagingTypeRecord("4G", "Box, fibreboard"));
                    _data["4G"].numeric = "21 to 25";
                    _data.Add("4H", new PackagingTypeRecord("4H", "Box, plastic"));
                    _data["4H"].numeric = "21 to 25";
                    _data.Add("5H", new PackagingTypeRecord("5H", "Bag, woven plastic"));
                    _data["5H"].numeric = "62 to 64";
                    _data.Add("5L", new PackagingTypeRecord("5L", "Bag, textile"));
                    _data["5L"].numeric = "62 to 64";
                    _data.Add("5M", new PackagingTypeRecord("5M", "Bag, paper"));
                    _data["5M"].numeric = "62 to 64";
                    _data.Add("6H", new PackagingTypeRecord("6H", "Composite packaging, plastic receptacle"));
                    _data["6H"].numeric = "24 or 25 or\r 33 or 34";
                    _data.Add("6P", new PackagingTypeRecord("6P", "Composite packaging, glass receptacle"));
                    _data["6P"].numeric = "23 or 24 or 25 or\r 33 or 34 or 62 or\r 63";
                    _data.Add("7A", new PackagingTypeRecord("7A", "Case, car"));
                    _data["7A"].description = "A type of portable container designed to store equipment for carriage in an autom" +
                        "obile.";
                    _data["7A"].numeric = "22 or 23";
                    _data.Add("7B", new PackagingTypeRecord("7B", "Case, wooden"));
                    _data["7B"].description = "A case made of wood for retaining substances or articles.";
                    _data["7B"].numeric = "24 or 25";
                    _data.Add("8A", new PackagingTypeRecord("8A", "Pallet, wooden"));
                    _data["8A"].description = "A platform or open-ended box, made of wood, on which goods are retained for ease " +
                        "of mechanical handling during transport and storage.";
                    _data["8A"].numeric = "24 or 25";
                    _data.Add("8B", new PackagingTypeRecord("8B", "Crate, wooden"));
                    _data["8B"].description = "A receptacle, made of wood, on which goods are retained for ease of mechanical ha" +
                        "ndling during transport and storage.";
                    _data["8B"].numeric = "23 to 27";
                    _data.Add("8C", new PackagingTypeRecord("8C", "Bundle, wooden"));
                    _data["8C"].description = "Loose or unpacked pieces of wood tied or wrapped together.";
                    _data["8C"].numeric = "16";
                    _data.Add("AA", new PackagingTypeRecord("AA", "Intermediate bulk container, rigid plastic"));
                    _data["AA"].numeric = "23 to 26";
                    _data.Add("AB", new PackagingTypeRecord("AB", "Receptacle, fibre"));
                    _data["AB"].description = "Containment vessel made of fibre used for retaining substances or articles.";
                    _data["AB"].numeric = "21 to 23 or\r 31 to 33 or\r 41 to 43";
                    _data.Add("AC", new PackagingTypeRecord("AC", "Receptacle, paper"));
                    _data["AC"].description = "Containment vessel made of paper for retaining substances or articles.";
                    _data["AC"].numeric = "21 to 23 or\r 31 to 33 or\r 41 to 43";
                    _data.Add("AD", new PackagingTypeRecord("AD", "Receptacle, wooden"));
                    _data["AD"].description = "Containment vessel made of wood for retaining substances or articles.";
                    _data["AD"].numeric = "21 to 23 or\r 31 to 33 or\r 41 to 43";
                    _data.Add("AE", new PackagingTypeRecord("AE", "Aerosol"));
                    _data["AE"].numeric = "42 or 43";
                    _data.Add("AF", new PackagingTypeRecord("AF", "Pallet, modular, collars 80cms * 60cms"));
                    _data["AF"].description = "Standard sized pallet of dimensions 80 centimeters by 60 centimeters (cms).";
                    _data["AF"].numeric = "92";
                    _data.Add("AG", new PackagingTypeRecord("AG", "Pallet, shrinkwrapped"));
                    _data["AG"].description = "Pallet load secured with transparent plastic film that has been wrapped around an" +
                        "d then shrunk tightly.";
                    _data["AG"].numeric = "92";
                    _data.Add("AH", new PackagingTypeRecord("AH", "Pallet, 100cms * 110cms"));
                    _data["AH"].description = "Standard sized pallet of dimensions 100centimeters by 110 centimeters (cms).";
                    _data["AH"].numeric = "92";
                    _data.Add("AI", new PackagingTypeRecord("AI", "Clamshell"));
                    _data["AI"].numeric = "21 to 23";
                    _data.Add("AJ", new PackagingTypeRecord("AJ", "Cone"));
                    _data["AJ"].description = "Container used in the transport of linear material such as yarn.";
                    _data["AJ"].numeric = "51";
                    _data.Add("AL", new PackagingTypeRecord("AL", "Ball"));
                    _data["AL"].description = "A spherical containment vessel for retaining substances or articles.";
                    _data["AL"].numeric = "46";
                    _data.Add("AM", new PackagingTypeRecord("AM", "Ampoule, non-protected"));
                    _data["AM"].numeric = "31";
                    _data.Add("AP", new PackagingTypeRecord("AP", "Ampoule, protected"));
                    _data["AP"].numeric = "31";
                    _data.Add("AT", new PackagingTypeRecord("AT", "Atomizer"));
                    _data["AT"].numeric = "42 or 43";
                    _data.Add("AV", new PackagingTypeRecord("AV", "Capsule"));
                    _data["AV"].numeric = "92";
                    _data.Add("B4", new PackagingTypeRecord("B4", "Belt"));
                    _data["B4"].description = "A band use to retain multiple articles together.";
                    _data["B4"].numeric = "93";
                    _data.Add("BA", new PackagingTypeRecord("BA", "Barrel"));
                    _data["BA"].numeric = "44 or 45";
                    _data.Add("BB", new PackagingTypeRecord("BB", "Bobbin"));
                    _data["BB"].numeric = "91";
                    _data.Add("BC", new PackagingTypeRecord("BC", "Bottlecrate / bottlerack"));
                    _data["BC"].numeric = "29";
                    _data.Add("BD", new PackagingTypeRecord("BD", "Board"));
                    _data["BD"].numeric = "16";
                    _data.Add("BE", new PackagingTypeRecord("BE", "Bundle"));
                    _data["BE"].numeric = "61 to 65";
                    _data.Add("BF", new PackagingTypeRecord("BF", "Balloon, non-protected"));
                    _data["BF"].numeric = "42 or 43";
                    _data.Add("BG", new PackagingTypeRecord("BG", "Bag"));
                    _data["BG"].description = "A receptacle made of flexible material with an open or closed top.";
                    _data["BG"].numeric = "62 to 64";
                    _data.Add("BH", new PackagingTypeRecord("BH", "Bunch"));
                    _data["BH"].numeric = "61 to 65";
                    _data.Add("BI", new PackagingTypeRecord("BI", "Bin"));
                    _data["BI"].numeric = "21 or 25";
                    _data.Add("BJ", new PackagingTypeRecord("BJ", "Bucket"));
                    _data["BJ"].numeric = "51";
                    _data.Add("BK", new PackagingTypeRecord("BK", "Basket"));
                    _data["BK"].numeric = "27";
                    _data.Add("BL", new PackagingTypeRecord("BL", "Bale, compressed"));
                    _data["BL"].numeric = "65";
                    _data.Add("BM", new PackagingTypeRecord("BM", "Basin"));
                    _data["BM"].numeric = "51";
                    _data.Add("BN", new PackagingTypeRecord("BN", "Bale, non-compressed"));
                    _data["BN"].numeric = "65";
                    _data.Add("BO", new PackagingTypeRecord("BO", "Bottle, non-protected, cylindrical"));
                    _data["BO"].description = "A narrow-necked cylindrical shaped vessel without external protective packing mat" +
                        "erial.";
                    _data["BO"].numeric = "32 or 33";
                    _data.Add("BP", new PackagingTypeRecord("BP", "Balloon, protected"));
                    _data["BP"].numeric = "42 or 43";
                    _data.Add("BQ", new PackagingTypeRecord("BQ", "Bottle, protected cylindrical"));
                    _data["BQ"].description = "A narrow-necked cylindrical shaped vessel with external protective packing materi" +
                        "al.";
                    _data["BQ"].numeric = "32 or 33";
                    _data.Add("BR", new PackagingTypeRecord("BR", "Bar"));
                    _data["BR"].numeric = "16";
                    _data.Add("BS", new PackagingTypeRecord("BS", "Bottle, non-protected, bulbous"));
                    _data["BS"].description = "A narrow-necked bulb shaped vessel without external protective packing material.";
                    _data["BS"].numeric = "42 or 43";
                    _data.Add("BT", new PackagingTypeRecord("BT", "Bolt"));
                    _data["BT"].numeric = "13";
                    _data.Add("BU", new PackagingTypeRecord("BU", "Butt"));
                    _data["BU"].numeric = "44 or 45";
                    _data.Add("BV", new PackagingTypeRecord("BV", "Bottle, protected bulbous"));
                    _data["BV"].description = "A narrow-necked bulb shaped vessel with external protective packing material.";
                    _data["BV"].numeric = "42 or 43";
                    _data.Add("BW", new PackagingTypeRecord("BW", "Box, for liquids"));
                    _data["BW"].numeric = "21 to 25";
                    _data.Add("BX", new PackagingTypeRecord("BX", "Box"));
                    _data["BX"].numeric = "21 to 25";
                    _data.Add("BY", new PackagingTypeRecord("BY", "Board, in bundle/bunch/truss"));
                    _data["BY"].numeric = "16";
                    _data.Add("BZ", new PackagingTypeRecord("BZ", "Bars, in bundle/bunch/truss"));
                    _data["BZ"].numeric = "16";
                    _data.Add("CA", new PackagingTypeRecord("CA", "Can, rectangular"));
                    _data["CA"].numeric = "22";
                    _data.Add("CB", new PackagingTypeRecord("CB", "Crate, beer"));
                    _data["CB"].numeric = "23 to 27";
                    _data.Add("CC", new PackagingTypeRecord("CC", "Churn"));
                    _data["CC"].numeric = "32 or 33";
                    _data.Add("CD", new PackagingTypeRecord("CD", "Can, with handle and spout"));
                    _data["CD"].numeric = "22";
                    _data.Add("CE", new PackagingTypeRecord("CE", "Creel"));
                    _data["CE"].numeric = "27";
                    _data.Add("CF", new PackagingTypeRecord("CF", "Coffer"));
                    _data["CF"].numeric = "24";
                    _data.Add("CG", new PackagingTypeRecord("CG", "Cage"));
                    _data["CG"].numeric = "26";
                    _data.Add("CH", new PackagingTypeRecord("CH", "Chest"));
                    _data["CH"].numeric = "25";
                    _data.Add("CI", new PackagingTypeRecord("CI", "Canister"));
                    _data["CI"].numeric = "21 or 22";
                    _data.Add("CJ", new PackagingTypeRecord("CJ", "Coffin"));
                    _data["CJ"].numeric = "54";
                    _data.Add("CK", new PackagingTypeRecord("CK", "Cask"));
                    _data["CK"].numeric = "44 or 45";
                    _data.Add("CL", new PackagingTypeRecord("CL", "Coil"));
                    _data["CL"].numeric = "14";
                    _data.Add("CM", new PackagingTypeRecord("CM", "Card"));
                    _data["CM"].description = "A flat package usually made of fibreboard from/to which product is often hung or " +
                        "attached.";
                    _data["CM"].numeric = "67";
                    _data.Add("CN", new PackagingTypeRecord("CN", "Container, not otherwise specified as transport equipment"));
                    _data["CN"].numeric = "25";
                    _data.Add("CO", new PackagingTypeRecord("CO", "Carboy, non-protected"));
                    _data["CO"].numeric = "43";
                    _data.Add("CP", new PackagingTypeRecord("CP", "Carboy, protected"));
                    _data["CP"].numeric = "43";
                    _data.Add("CQ", new PackagingTypeRecord("CQ", "Cartridge"));
                    _data["CQ"].description = "Package containing a charge such as propelling explosive for firearms or ink tone" +
                        "r for a printer.";
                    _data["CQ"].numeric = "92";
                    _data.Add("CR", new PackagingTypeRecord("CR", "Crate"));
                    _data["CR"].numeric = "24 to 25";
                    _data.Add("CS", new PackagingTypeRecord("CS", "Case"));
                    _data["CS"].numeric = "21 to 25";
                    _data.Add("CT", new PackagingTypeRecord("CT", "Carton"));
                    _data["CT"].numeric = "22 to 24";
                    _data.Add("CU", new PackagingTypeRecord("CU", "Cup"));
                    _data["CU"].numeric = "51";
                    _data.Add("CV", new PackagingTypeRecord("CV", "Cover"));
                    _data["CV"].numeric = "67";
                    _data.Add("CW", new PackagingTypeRecord("CW", "Cage, roll"));
                    _data["CW"].numeric = "26";
                    _data.Add("CX", new PackagingTypeRecord("CX", "Can, cylindrical"));
                    _data["CX"].numeric = "32";
                    _data.Add("CY", new PackagingTypeRecord("CY", "Cylinder"));
                    _data["CY"].numeric = "12";
                    _data.Add("CZ", new PackagingTypeRecord("CZ", "Canvas"));
                    _data["CZ"].numeric = "67";
                    _data.Add("DA", new PackagingTypeRecord("DA", "Crate, multiple layer, plastic"));
                    _data["DA"].numeric = "23 to 25 or 27";
                    _data.Add("DB", new PackagingTypeRecord("DB", "Crate, multiple layer, wooden"));
                    _data["DB"].numeric = "23 to 25 or 27";
                    _data.Add("DC", new PackagingTypeRecord("DC", "Crate, multiple layer, cardboard"));
                    _data["DC"].numeric = "23 to 25 or 27";
                    _data.Add("DG", new PackagingTypeRecord("DG", "Cage, Commonwealth Handling Equipment Pool  (CHEP)"));
                    _data["DG"].numeric = "26";
                    _data.Add("DH", new PackagingTypeRecord("DH", "Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox"));
                    _data["DH"].description = "A box mounted on a pallet base under the control of CHEP.";
                    _data["DH"].numeric = "27";
                    _data.Add("DI", new PackagingTypeRecord("DI", "Drum, iron"));
                    _data["DI"].numeric = "34";
                    _data.Add("DJ", new PackagingTypeRecord("DJ", "Demijohn, non-protected"));
                    _data["DJ"].numeric = "43";
                    _data.Add("DK", new PackagingTypeRecord("DK", "Crate, bulk, cardboard"));
                    _data["DK"].numeric = "23 to 25 or 27";
                    _data.Add("DL", new PackagingTypeRecord("DL", "Crate, bulk, plastic"));
                    _data["DL"].numeric = "23 to 25 or 27";
                    _data.Add("DM", new PackagingTypeRecord("DM", "Crate, bulk, wooden"));
                    _data["DM"].numeric = "23 to 25 or 27";
                    _data.Add("DN", new PackagingTypeRecord("DN", "Dispenser"));
                    _data["DN"].numeric = "93";
                    _data.Add("DP", new PackagingTypeRecord("DP", "Demijohn, protected"));
                    _data["DP"].numeric = "43";
                    _data.Add("DR", new PackagingTypeRecord("DR", "Drum"));
                    _data["DR"].numeric = "34";
                    _data.Add("DS", new PackagingTypeRecord("DS", "Tray, one layer no cover, plastic"));
                    _data["DS"].numeric = "27";
                    _data.Add("DT", new PackagingTypeRecord("DT", "Tray, one layer no cover, wooden"));
                    _data["DT"].numeric = "27";
                    _data.Add("DU", new PackagingTypeRecord("DU", "Tray, one layer no cover, polystyrene"));
                    _data["DU"].numeric = "27";
                    _data.Add("DV", new PackagingTypeRecord("DV", "Tray, one layer no cover, cardboard"));
                    _data["DV"].numeric = "27";
                    _data.Add("DW", new PackagingTypeRecord("DW", "Tray, two layers no cover, plastic tray"));
                    _data["DW"].numeric = "27 or 29";
                    _data.Add("DX", new PackagingTypeRecord("DX", "Tray, two layers no cover, wooden"));
                    _data["DX"].numeric = "27 or 29";
                    _data.Add("DY", new PackagingTypeRecord("DY", "Tray, two layers no cover, cardboard"));
                    _data["DY"].numeric = "27 or 29";
                    _data.Add("EC", new PackagingTypeRecord("EC", "Bag, plastic"));
                    _data["EC"].numeric = "62 to 64";
                    _data.Add("ED", new PackagingTypeRecord("ED", "Case, with pallet base"));
                    _data["ED"].numeric = "23 to 25";
                    _data.Add("EE", new PackagingTypeRecord("EE", "Case, with pallet base, wooden"));
                    _data["EE"].numeric = "23 to 25";
                    _data.Add("EF", new PackagingTypeRecord("EF", "Case, with pallet base, cardboard"));
                    _data["EF"].numeric = "23 to 25";
                    _data.Add("EG", new PackagingTypeRecord("EG", "Case, with pallet base, plastic"));
                    _data["EG"].numeric = "23 to 25";
                    _data.Add("EH", new PackagingTypeRecord("EH", "Case, with pallet base, metal"));
                    _data["EH"].numeric = "23 to 25";
                    _data.Add("EI", new PackagingTypeRecord("EI", "Case, isothermic"));
                    _data["EI"].numeric = "22 to 25";
                    _data.Add("EN", new PackagingTypeRecord("EN", "Envelope"));
                    _data["EN"].numeric = "67";
                    _data.Add("FB", new PackagingTypeRecord("FB", "Flexibag"));
                    _data["FB"].description = "A flexible containment bag made of plastic, typically for the transportation bulk" +
                        " non-hazardous cargoes using standard size shipping containers.";
                    _data["FB"].numeric = "65";
                    _data.Add("FC", new PackagingTypeRecord("FC", "Crate, fruit"));
                    _data["FC"].numeric = "23 to 27";
                    _data.Add("FD", new PackagingTypeRecord("FD", "Crate, framed"));
                    _data["FD"].numeric = "26";
                    _data.Add("FE", new PackagingTypeRecord("FE", "Flexitank"));
                    _data["FE"].description = "A flexible containment tank made of plastic, typically for the transportation bul" +
                        "k non-hazardous cargoes using standard size shipping containers.";
                    _data["FE"].numeric = "65";
                    _data.Add("FI", new PackagingTypeRecord("FI", "Firkin"));
                    _data["FI"].numeric = "44 or 45";
                    _data.Add("FL", new PackagingTypeRecord("FL", "Flask"));
                    _data["FL"].numeric = "42 or 43";
                    _data.Add("FO", new PackagingTypeRecord("FO", "Footlocker"));
                    _data["FO"].numeric = "23";
                    _data.Add("FP", new PackagingTypeRecord("FP", "Filmpack"));
                    _data["FP"].numeric = "67";
                    _data.Add("FR", new PackagingTypeRecord("FR", "Frame"));
                    _data["FR"].numeric = "26";
                    _data.Add("FT", new PackagingTypeRecord("FT", "Foodtainer"));
                    _data["FT"].numeric = "21 to 23";
                    _data.Add("FW", new PackagingTypeRecord("FW", "Cart, flatbed"));
                    _data["FW"].description = "Wheeled flat bedded device on which trays or other regular shaped items are packe" +
                        "d for transportation purposes.";
                    _data["FW"].numeric = "94";
                    _data.Add("FX", new PackagingTypeRecord("FX", "Bag, flexible container"));
                    _data["FX"].numeric = "61 to 66";
                    _data.Add("GB", new PackagingTypeRecord("GB", "Bottle, gas"));
                    _data["GB"].description = "A narrow-necked metal cylinder for retention of liquefied or compressed gas.";
                    _data["GB"].numeric = "31 or 35";
                    _data.Add("GI", new PackagingTypeRecord("GI", "Girder"));
                    _data["GI"].numeric = "16";
                    _data.Add("GL", new PackagingTypeRecord("GL", "Container, gallon"));
                    _data["GL"].description = "A container with a capacity of one gallon.";
                    _data["GL"].numeric = "32";
                    _data.Add("GR", new PackagingTypeRecord("GR", "Receptacle, glass"));
                    _data["GR"].description = "Containment vessel made of glass for retaining substances or articles.";
                    _data["GR"].numeric = "21 to 23 or\r 31 to 33 or\r 41 to 43";
                    _data.Add("GU", new PackagingTypeRecord("GU", "Tray, containing horizontally stacked flat items"));
                    _data["GU"].description = "Tray containing flat items stacked on top of one another.";
                    _data["GU"].numeric = "27";
                    _data.Add("GY", new PackagingTypeRecord("GY", "Bag, gunny"));
                    _data["GY"].description = "A sack made of gunny or burlap, used for transporting coarse commodities, such as" +
                        " grains, potatoes, and other agricultural products.";
                    _data["GY"].numeric = "63 to 64";
                    _data.Add("GZ", new PackagingTypeRecord("GZ", "Girders, in bundle/bunch/truss"));
                    _data["GZ"].numeric = "16";
                    _data.Add("HA", new PackagingTypeRecord("HA", "Basket, with handle, plastic"));
                    _data["HA"].numeric = "27";
                    _data.Add("HB", new PackagingTypeRecord("HB", "Basket, with handle, wooden"));
                    _data["HB"].numeric = "27";
                    _data.Add("HC", new PackagingTypeRecord("HC", "Basket, with handle, cardboard"));
                    _data["HC"].numeric = "27";
                    _data.Add("HG", new PackagingTypeRecord("HG", "Hogshead"));
                    _data["HG"].numeric = "44 or 45";
                    _data.Add("HN", new PackagingTypeRecord("HN", "Hanger"));
                    _data["HN"].description = "A purpose shaped device with a hook at the top for hanging items from a rail.";
                    _data["HN"].numeric = "93";
                    _data.Add("HR", new PackagingTypeRecord("HR", "Hamper"));
                    _data["HR"].numeric = "23";
                    _data.Add("IA", new PackagingTypeRecord("IA", "Package, display, wooden"));
                    _data["IA"].numeric = "21 to 23";
                    _data.Add("IB", new PackagingTypeRecord("IB", "Package, display, cardboard"));
                    _data["IB"].numeric = "21 to 23";
                    _data.Add("IC", new PackagingTypeRecord("IC", "Package, display, plastic"));
                    _data["IC"].numeric = "21 to 23";
                    _data.Add("ID", new PackagingTypeRecord("ID", "Package, display, metal"));
                    _data["ID"].numeric = "21 to 23";
                    _data.Add("IE", new PackagingTypeRecord("IE", "Package, show"));
                    _data["IE"].numeric = "21 to 23";
                    _data.Add("IF", new PackagingTypeRecord("IF", "Package, flow"));
                    _data["IF"].description = "A flexible tubular package or skin, possibly transparent, often used for containm" +
                        "ent of foodstuffs (e.g. salami sausage).";
                    _data["IF"].numeric = "61 or 62";
                    _data.Add("IG", new PackagingTypeRecord("IG", "Package, paper wrapped"));
                    _data["IG"].numeric = "21 to 23";
                    _data.Add("IH", new PackagingTypeRecord("IH", "Drum, plastic"));
                    _data["IH"].numeric = "34";
                    _data.Add("IK", new PackagingTypeRecord("IK", "Package, cardboard, with bottle grip-holes"));
                    _data["IK"].description = "Packaging material made out of cardboard that facilitates the separation of indiv" +
                        "idual glass or plastic bottles.";
                    _data["IK"].numeric = "21 to 23";
                    _data.Add("IL", new PackagingTypeRecord("IL", "Tray, rigid, lidded stackable (CEN TS 14482:2002)"));
                    _data["IL"].description = "Lidded stackable rigid tray compliant with CEN TS 14482:2002.";
                    _data["IL"].numeric = "27";
                    _data.Add("IN", new PackagingTypeRecord("IN", "Ingot"));
                    _data["IN"].numeric = "17";
                    _data.Add("IZ", new PackagingTypeRecord("IZ", "Ingots, in bundle/bunch/truss"));
                    _data["IZ"].numeric = "17";
                    _data.Add("JB", new PackagingTypeRecord("JB", "Bag, jumbo"));
                    _data["JB"].description = "A flexible containment bag, widely used for storage, transportation and handling " +
                        "of powder, flake or granular materials. Typically constructed from woven polypro" +
                        "pylene (PP) fabric in the form of cubic bags.";
                    _data["JB"].numeric = "65";
                    _data.Add("JC", new PackagingTypeRecord("JC", "Jerrican, rectangular"));
                    _data["JC"].numeric = "23";
                    _data.Add("JG", new PackagingTypeRecord("JG", "Jug"));
                    _data["JG"].numeric = "41";
                    _data.Add("JR", new PackagingTypeRecord("JR", "Jar"));
                    _data["JR"].numeric = "41";
                    _data.Add("JT", new PackagingTypeRecord("JT", "Jutebag"));
                    _data["JT"].numeric = "61 or 65";
                    _data.Add("JY", new PackagingTypeRecord("JY", "Jerrican, cylindrical"));
                    _data["JY"].numeric = "33";
                    _data.Add("KG", new PackagingTypeRecord("KG", "Keg"));
                    _data["KG"].numeric = "44 or 45";
                    _data.Add("KI", new PackagingTypeRecord("KI", "Kit"));
                    _data["KI"].description = "A set of articles or implements used for a specific purpose.";
                    _data["KI"].numeric = "92";
                    _data.Add("LE", new PackagingTypeRecord("LE", "Luggage"));
                    _data["LE"].description = "A collection of bags, cases and/or containers which hold personal belongings for " +
                        "a journey.";
                    _data["LE"].numeric = "21 to 23 or\r 61 to 63";
                    _data.Add("LG", new PackagingTypeRecord("LG", "Log"));
                    _data["LG"].numeric = "12";
                    _data.Add("LT", new PackagingTypeRecord("LT", "Lot"));
                    _data["LT"].numeric = "01 to 03";
                    _data.Add("LU", new PackagingTypeRecord("LU", "Lug"));
                    _data["LU"].description = "A wooden box for the transportation and storage of fruit or vegetables.";
                    _data["LU"].numeric = "23";
                    _data.Add("LV", new PackagingTypeRecord("LV", "Liftvan"));
                    _data["LV"].description = "A wooden or metal container used for packing household goods and personal effects" +
                        ".";
                    _data["LV"].numeric = "22 to 24";
                    _data.Add("LZ", new PackagingTypeRecord("LZ", "Logs, in bundle/bunch/truss"));
                    _data["LZ"].numeric = "12";
                    _data.Add("MA", new PackagingTypeRecord("MA", "Crate, metal"));
                    _data["MA"].description = "Containment box made of metal for retaining substances or articles.";
                    _data["MA"].numeric = "23 to 25 or 27";
                    _data.Add("MB", new PackagingTypeRecord("MB", "Bag, multiply"));
                    _data["MB"].numeric = "62 to 64";
                    _data.Add("MC", new PackagingTypeRecord("MC", "Crate, milk"));
                    _data["MC"].numeric = "27";
                    _data.Add("ME", new PackagingTypeRecord("ME", "Container, metal"));
                    _data["ME"].description = "A type of containment box made of metal for retaining substances or articles, not" +
                        " otherwise specified as transport equipment.";
                    _data["ME"].numeric = "23 to 25 or 27";
                    _data.Add("MR", new PackagingTypeRecord("MR", "Receptacle, metal"));
                    _data["MR"].description = "Containment vessel made of metal for retaining substances or articles.";
                    _data["MR"].numeric = "21 to 23 or\r 31 to 33";
                    _data.Add("MS", new PackagingTypeRecord("MS", "Sack, multi-wall"));
                    _data["MS"].numeric = "62 to 64";
                    _data.Add("MT", new PackagingTypeRecord("MT", "Mat"));
                    _data["MT"].numeric = "67";
                    _data.Add("MW", new PackagingTypeRecord("MW", "Receptacle, plastic wrapped"));
                    _data["MW"].description = "Containment vessel wrapped with plastic for retaining substances or articles.";
                    _data["MW"].numeric = "21 to 23 or\r 31 to 33 or\r 41 to 43 or\r 61 to 63";
                    _data.Add("MX", new PackagingTypeRecord("MX", "Matchbox"));
                    _data["MX"].numeric = "21";
                    _data.Add("NA", new PackagingTypeRecord("NA", "Not available"));
                    _data["NA"].numeric = "0";
                    _data.Add("NE", new PackagingTypeRecord("NE", "Unpacked or unpackaged"));
                    _data["NE"].numeric = "0";
                    _data.Add("NF", new PackagingTypeRecord("NF", "Unpacked or unpackaged, single unit"));
                    _data["NF"].numeric = "0";
                    _data.Add("NG", new PackagingTypeRecord("NG", "Unpacked or unpackaged, multiple units"));
                    _data["NG"].numeric = "0";
                    _data.Add("NS", new PackagingTypeRecord("NS", "Nest"));
                    _data["NS"].numeric = "24";
                    _data.Add("NT", new PackagingTypeRecord("NT", "Net"));
                    _data["NT"].numeric = "66";
                    _data.Add("NU", new PackagingTypeRecord("NU", "Net, tube, plastic"));
                    _data["NU"].numeric = "66";
                    _data.Add("NV", new PackagingTypeRecord("NV", "Net, tube, textile"));
                    _data["NV"].numeric = "66";
                    _data.Add("OA", new PackagingTypeRecord("OA", "Pallet, CHEP 40 cm x 60 cm"));
                    _data["OA"].description = "Commonwealth Handling Equipment Pool (CHEP) standard pallet of dimensions 40 cent" +
                        "imeters x 60 centimeters.";
                    _data["OA"].numeric = "92";
                    _data.Add("OB", new PackagingTypeRecord("OB", "Pallet, CHEP 80 cm x 120 cm"));
                    _data["OB"].description = "Commonwealth Handling Equipment Pool (CHEP) standard pallet of dimensions 80 cent" +
                        "imeters x 120 centimeters.";
                    _data["OB"].numeric = "92";
                    _data.Add("OC", new PackagingTypeRecord("OC", "Pallet, CHEP 100 cm x 120 cm"));
                    _data["OC"].description = "Commonwealth Handling Equipment Pool (CHEP) standard pallet of dimensions 100 cen" +
                        "timeters x 120 centimeters.";
                    _data["OC"].numeric = "92";
                    _data.Add("OD", new PackagingTypeRecord("OD", "Pallet, AS 4068-1993"));
                    _data["OD"].description = "Australian standard pallet of dimensions 115.5 centimeters x 116.5 centimeters.";
                    _data["OD"].numeric = "92";
                    _data.Add("OE", new PackagingTypeRecord("OE", "Pallet, ISO T11"));
                    _data["OE"].description = "ISO standard pallet of dimensions 110 centimeters x 110 centimeters, prevalent in" +
                        " Asia - Pacific region.";
                    _data["OE"].numeric = "92";
                    _data.Add("OF", new PackagingTypeRecord("OF", "Platform, unspecified weight or dimension"));
                    _data["OF"].description = "A pallet equivalent shipping platform of unknown dimensions or unknown weight.";
                    _data["OF"].numeric = "92";
                    _data.Add("OK", new PackagingTypeRecord("OK", "Block"));
                    _data["OK"].description = "A solid piece of a hard substance, such as granite, having one or more flat sides" +
                        ".";
                    _data["OK"].numeric = "17";
                    _data.Add("OT", new PackagingTypeRecord("OT", "Octabin"));
                    _data["OT"].description = "A standard cardboard container of large dimensions for storing for example vegeta" +
                        "bles, granules of plastics or other dry products.";
                    _data["OT"].numeric = "25";
                    _data.Add("OU", new PackagingTypeRecord("OU", "Container, outer"));
                    _data["OU"].description = "A type of containment box that serves as the outer shipping container, not otherw" +
                        "ise specified as transport equipment.";
                    _data["OU"].numeric = "23 to 25 or 27";
                    _data.Add("P2", new PackagingTypeRecord("P2", "Pan"));
                    _data["P2"].description = "A shallow, wide, open container, usually of metal.";
                    _data["P2"].numeric = "51";
                    _data.Add("PA", new PackagingTypeRecord("PA", "Packet"));
                    _data["PA"].description = "Small package.";
                    _data["PA"].numeric = "21 to 23";
                    _data.Add("PB", new PackagingTypeRecord("PB", "Pallet, box Combined open-ended box and pallet"));
                    _data["PB"].numeric = "92";
                    _data.Add("PC", new PackagingTypeRecord("PC", "Parcel"));
                    _data["PC"].numeric = "21 to 23 or\r 61 to 63";
                    _data.Add("PD", new PackagingTypeRecord("PD", "Pallet, modular, collars 80cms * 100cms"));
                    _data["PD"].description = "Standard sized pallet of dimensions 80 centimeters by 100 centimeters (cms).";
                    _data["PD"].numeric = "92";
                    _data.Add("PE", new PackagingTypeRecord("PE", "Pallet, modular, collars 80cms * 120cms"));
                    _data["PE"].description = "Standard sized pallet of dimensions 80 centimeters by 120 centimeters (cms).";
                    _data["PE"].numeric = "92";
                    _data.Add("PF", new PackagingTypeRecord("PF", "Pen"));
                    _data["PF"].description = "A small open top enclosure for retaining animals.";
                    _data["PF"].numeric = "26 or 27";
                    _data.Add("PG", new PackagingTypeRecord("PG", "Plate"));
                    _data["PG"].numeric = "15";
                    _data.Add("PH", new PackagingTypeRecord("PH", "Pitcher"));
                    _data["PH"].numeric = "41";
                    _data.Add("PI", new PackagingTypeRecord("PI", "Pipe"));
                    _data["PI"].numeric = "11";
                    _data.Add("PJ", new PackagingTypeRecord("PJ", "Punnet"));
                    _data["PJ"].numeric = "27";
                    _data.Add("PK", new PackagingTypeRecord("PK", "Package"));
                    _data["PK"].description = "Standard packaging unit.";
                    _data["PK"].numeric = "21 to 23";
                    _data.Add("PL", new PackagingTypeRecord("PL", "Pail"));
                    _data["PL"].numeric = "51";
                    _data.Add("PN", new PackagingTypeRecord("PN", "Plank"));
                    _data["PN"].numeric = "16";
                    _data.Add("PO", new PackagingTypeRecord("PO", "Pouch"));
                    _data["PO"].numeric = "61";
                    _data.Add("PP", new PackagingTypeRecord("PP", "Piece"));
                    _data["PP"].description = "A loose or unpacked article.";
                    _data["PP"].numeric = "19";
                    _data.Add("PR", new PackagingTypeRecord("PR", "Receptacle, plastic"));
                    _data["PR"].description = "Containment vessel made of plastic for retaining substances or articles.";
                    _data["PR"].numeric = "21 to 23 or\r 31 to 33 or\r 41 to 43 or\r 61 to 63";
                    _data.Add("PT", new PackagingTypeRecord("PT", "Pot"));
                    _data["PT"].numeric = "41";
                    _data.Add("PU", new PackagingTypeRecord("PU", "Tray"));
                    _data["PU"].numeric = "27";
                    _data.Add("PV", new PackagingTypeRecord("PV", "Pipes, in bundle/bunch/truss"));
                    _data["PV"].numeric = "11";
                    _data.Add("PX", new PackagingTypeRecord("PX", "Pallet"));
                    _data["PX"].description = "Platform or open-ended box, usually made of wood, on which goods are retained for" +
                        " ease of mechanical handling during transport and storage.";
                    _data["PX"].numeric = "92";
                    _data.Add("PY", new PackagingTypeRecord("PY", "Plates, in bundle/bunch/truss"));
                    _data["PY"].numeric = "15";
                    _data.Add("PZ", new PackagingTypeRecord("PZ", "Planks, in bundle/bunch/truss"));
                    _data["PZ"].numeric = "16";
                    _data.Add("QA", new PackagingTypeRecord("QA", "Drum, steel, non-removable head"));
                    _data["QA"].numeric = "34";
                    _data.Add("QB", new PackagingTypeRecord("QB", "Drum, steel, removable head"));
                    _data["QB"].numeric = "34";
                    _data.Add("QC", new PackagingTypeRecord("QC", "Drum, aluminium, non-removable head"));
                    _data["QC"].numeric = "34";
                    _data.Add("QD", new PackagingTypeRecord("QD", "Drum, aluminium, removable head"));
                    _data["QD"].numeric = "34";
                    _data.Add("QF", new PackagingTypeRecord("QF", "Drum, plastic, non-removable head"));
                    _data["QF"].numeric = "34";
                    _data.Add("QG", new PackagingTypeRecord("QG", "Drum, plastic, removable head"));
                    _data["QG"].numeric = "34";
                    _data.Add("QH", new PackagingTypeRecord("QH", "Barrel, wooden, bung type"));
                    _data["QH"].numeric = "44 or 45";
                    _data.Add("QJ", new PackagingTypeRecord("QJ", "Barrel, wooden, removable head"));
                    _data["QJ"].numeric = "44 or 45";
                    _data.Add("QK", new PackagingTypeRecord("QK", "Jerrican, steel, non-removable head"));
                    _data["QK"].numeric = "23 or 33";
                    _data.Add("QL", new PackagingTypeRecord("QL", "Jerrican, steel, removable head"));
                    _data["QL"].numeric = "23 or 33";
                    _data.Add("QM", new PackagingTypeRecord("QM", "Jerrican, plastic, non-removable head"));
                    _data["QM"].numeric = "23 or 33";
                    _data.Add("QN", new PackagingTypeRecord("QN", "Jerrican, plastic, removable head"));
                    _data["QN"].numeric = "23 or 33";
                    _data.Add("QP", new PackagingTypeRecord("QP", "Box, wooden, natural wood, ordinary"));
                    _data["QP"].numeric = "21 to 25";
                    _data.Add("QQ", new PackagingTypeRecord("QQ", "Box, wooden, natural wood, with sift proof walls"));
                    _data["QQ"].numeric = "21 to 25";
                    _data.Add("QR", new PackagingTypeRecord("QR", "Box, plastic, expanded"));
                    _data["QR"].numeric = "21 to 25";
                    _data.Add("QS", new PackagingTypeRecord("QS", "Box, plastic, solid"));
                    _data["QS"].numeric = "21 to 25";
                    _data.Add("RD", new PackagingTypeRecord("RD", "Rod"));
                    _data["RD"].numeric = "12";
                    _data.Add("RG", new PackagingTypeRecord("RG", "Ring"));
                    _data["RG"].numeric = "14";
                    _data.Add("RJ", new PackagingTypeRecord("RJ", "Rack, clothing hanger"));
                    _data["RJ"].numeric = "93";
                    _data.Add("RK", new PackagingTypeRecord("RK", "Rack"));
                    _data["RK"].numeric = "93";
                    _data.Add("RL", new PackagingTypeRecord("RL", "Reel"));
                    _data["RL"].description = "Cylindrical rotatory device with a rim at each end on which materials are wound.";
                    _data["RL"].numeric = "91";
                    _data.Add("RO", new PackagingTypeRecord("RO", "Roll"));
                    _data["RO"].numeric = "13";
                    _data.Add("RT", new PackagingTypeRecord("RT", "Rednet"));
                    _data["RT"].description = "Containment material made of red mesh netting for retaining articles (e.g. trees)" +
                        ".";
                    _data["RT"].numeric = "66";
                    _data.Add("RZ", new PackagingTypeRecord("RZ", "Rods, in bundle/bunch/truss"));
                    _data["RZ"].numeric = "12";
                    _data.Add("SA", new PackagingTypeRecord("SA", "Sack"));
                    _data["SA"].numeric = "65";
                    _data.Add("SB", new PackagingTypeRecord("SB", "Slab"));
                    _data["SB"].numeric = "16 or 17";
                    _data.Add("SC", new PackagingTypeRecord("SC", "Crate, shallow"));
                    _data["SC"].numeric = "27";
                    _data.Add("SD", new PackagingTypeRecord("SD", "Spindle"));
                    _data["SD"].numeric = "91";
                    _data.Add("SE", new PackagingTypeRecord("SE", "Sea-chest"));
                    _data["SE"].numeric = "22 or 23";
                    _data.Add("SH", new PackagingTypeRecord("SH", "Sachet"));
                    _data["SH"].numeric = "61";
                    _data.Add("SI", new PackagingTypeRecord("SI", "Skid"));
                    _data["SI"].description = "A low movable platform or pallet to facilitate the handling and transport of good" +
                        "s.";
                    _data["SI"].numeric = "92";
                    _data.Add("SK", new PackagingTypeRecord("SK", "Case, skeleton"));
                    _data["SK"].numeric = "26";
                    _data.Add("SL", new PackagingTypeRecord("SL", "Slipsheet"));
                    _data["SL"].description = "Hard plastic sheeting primarily used as the base on which to stack goods to optim" +
                        "ise the space within a container. May be used as an alternative to a palletized " +
                        "packaging.";
                    _data["SL"].numeric = "67";
                    _data.Add("SM", new PackagingTypeRecord("SM", "Sheetmetal"));
                    _data["SM"].numeric = "15";
                    _data.Add("SO", new PackagingTypeRecord("SO", "Spool"));
                    _data["SO"].description = "A packaging container used in the transport of such items as wire, cable, tape an" +
                        "d yarn.";
                    _data["SO"].numeric = "91";
                    _data.Add("SP", new PackagingTypeRecord("SP", "Sheet, plastic wrapping"));
                    _data["SP"].numeric = "15";
                    _data.Add("SS", new PackagingTypeRecord("SS", "Case, steel"));
                    _data["SS"].numeric = "21 to 25";
                    _data.Add("ST", new PackagingTypeRecord("ST", "Sheet"));
                    _data["ST"].numeric = "15";
                    _data.Add("SU", new PackagingTypeRecord("SU", "Suitcase"));
                    _data["SU"].numeric = "21 to 23 or\r 61 to 63";
                    _data.Add("SV", new PackagingTypeRecord("SV", "Envelope, steel"));
                    _data["SV"].numeric = "67";
                    _data.Add("SW", new PackagingTypeRecord("SW", "Shrinkwrapped"));
                    _data["SW"].description = "Goods retained in a transparent plastic film that has been wrapped around and the" +
                        "n shrunk tightly on to the goods.";
                    _data["SW"].numeric = "67";
                    _data.Add("SX", new PackagingTypeRecord("SX", "Set"));
                    _data["SX"].numeric = "11 to 45";
                    _data.Add("SY", new PackagingTypeRecord("SY", "Sleeve"));
                    _data["SY"].numeric = "69";
                    _data.Add("SZ", new PackagingTypeRecord("SZ", "Sheets, in bundle/bunch/truss"));
                    _data["SZ"].numeric = "15";
                    _data.Add("T1", new PackagingTypeRecord("T1", "Tablet"));
                    _data["T1"].description = "A loose or unpacked article in the form of a bar, block or piece.";
                    _data["T1"].numeric = "16";
                    _data.Add("TB", new PackagingTypeRecord("TB", "Tub"));
                    _data["TB"].numeric = "51";
                    _data.Add("TC", new PackagingTypeRecord("TC", "Tea-chest"));
                    _data["TC"].numeric = "21 to 23";
                    _data.Add("TD", new PackagingTypeRecord("TD", "Tube, collapsible"));
                    _data["TD"].numeric = "61 to 65";
                    _data.Add("TE", new PackagingTypeRecord("TE", "Tyre"));
                    _data["TE"].description = "A ring made of rubber and/or metal surrounding a wheel.";
                    _data["TE"].numeric = "93";
                    _data.Add("TG", new PackagingTypeRecord("TG", "Tank container, generic"));
                    _data["TG"].description = "A specially constructed container for transporting liquids and gases in bulk.";
                    _data["TG"].numeric = "93";
                    _data.Add("TI", new PackagingTypeRecord("TI", "Tierce"));
                    _data["TI"].numeric = "44";
                    _data.Add("TK", new PackagingTypeRecord("TK", "Tank, rectangular"));
                    _data["TK"].numeric = "24 or 25";
                    _data.Add("TL", new PackagingTypeRecord("TL", "Tub, with lid"));
                    _data["TL"].numeric = "51";
                    _data.Add("TN", new PackagingTypeRecord("TN", "Tin"));
                    _data["TN"].numeric = "21 or 22";
                    _data.Add("TO", new PackagingTypeRecord("TO", "Tun"));
                    _data["TO"].numeric = "44 or 45";
                    _data.Add("TR", new PackagingTypeRecord("TR", "Trunk"));
                    _data["TR"].numeric = "24 or 25";
                    _data.Add("TS", new PackagingTypeRecord("TS", "Truss"));
                    _data["TS"].numeric = "16";
                    _data.Add("TT", new PackagingTypeRecord("TT", "Bag, tote"));
                    _data["TT"].description = "A capacious bag or basket.";
                    _data["TT"].numeric = "62 or 63";
                    _data.Add("TU", new PackagingTypeRecord("TU", "Tube"));
                    _data["TU"].numeric = "11";
                    _data.Add("TV", new PackagingTypeRecord("TV", "Tube, with nozzle"));
                    _data["TV"].description = "A tube made of plastic, metal or cardboard fitted with a nozzle, containing a liq" +
                        "uid or semi-liquid product, e.g. silicon.";
                    _data["TV"].numeric = "31 or 32";
                    _data.Add("TW", new PackagingTypeRecord("TW", "Pallet, triwall"));
                    _data["TW"].description = "A lightweight pallet made from heavy duty corrugated board.";
                    _data["TW"].numeric = "92";
                    _data.Add("TY", new PackagingTypeRecord("TY", "Tank, cylindrical"));
                    _data["TY"].numeric = "34 or 35";
                    _data.Add("TZ", new PackagingTypeRecord("TZ", "Tubes, in bundle/bunch/truss"));
                    _data["TZ"].numeric = "11";
                    _data.Add("UC", new PackagingTypeRecord("UC", "Uncaged"));
                    _data["UC"].numeric = "0";
                    _data.Add("UN", new PackagingTypeRecord("UN", "Unit"));
                    _data["UN"].description = "A type of package composed of a single item or object, not otherwise specified as" +
                        " a unit of transport equipment.";
                    _data["UN"].numeric = "23 to 25 or 27";
                    _data.Add("VA", new PackagingTypeRecord("VA", "Vat"));
                    _data["VA"].numeric = "35";
                    _data.Add("VG", new PackagingTypeRecord("VG", "Bulk, gas (at 1031 mbar and 15°C)"));
                    _data["VG"].numeric = "6";
                    _data.Add("VI", new PackagingTypeRecord("VI", "Vial"));
                    _data["VI"].numeric = "31";
                    _data.Add("VK", new PackagingTypeRecord("VK", "Vanpack"));
                    _data["VK"].description = "A type of wooden crate.";
                    _data["VK"].numeric = "99";
                    _data.Add("VL", new PackagingTypeRecord("VL", "Bulk, liquid"));
                    _data["VL"].numeric = "4";
                    _data.Add("VO", new PackagingTypeRecord("VO", "Bulk, solid, large particles (nodules)"));
                    _data["VO"].numeric = "3";
                    _data.Add("VP", new PackagingTypeRecord("VP", "Vacuum-packed"));
                    _data["VP"].numeric = "67";
                    _data.Add("VQ", new PackagingTypeRecord("VQ", "Bulk, liquefied gas (at abnormal temperature/pressure)"));
                    _data["VQ"].numeric = "5";
                    _data.Add("VN", new PackagingTypeRecord("VN", "Vehicle"));
                    _data["VN"].description = "A self-propelled means of conveyance.";
                    _data["VN"].numeric = "93";
                    _data.Add("VR", new PackagingTypeRecord("VR", "Bulk, solid, granular particles (grains)"));
                    _data["VR"].numeric = "2";
                    _data.Add("VS", new PackagingTypeRecord("VS", "Bulk, scrap metal"));
                    _data["VS"].description = "Loose or unpacked scrap metal transported in bulk form.";
                    _data["VS"].numeric = "9";
                    _data.Add("VY", new PackagingTypeRecord("VY", "Bulk, solid, fine particles (powders)"));
                    _data["VY"].numeric = "1";
                    _data.Add("WA", new PackagingTypeRecord("WA", "Intermediate bulk container"));
                    _data["WA"].description = "A reusable container made of metal, plastic, textile, wood or composite materials" +
                        " used to facilitate transportation of bulk solids and liquids in manageable volu" +
                        "mes.";
                    _data["WA"].numeric = "23 to 26 or\r 62 to 64";
                    _data.Add("WB", new PackagingTypeRecord("WB", "Wickerbottle"));
                    _data["WB"].numeric = "42 or 43";
                    _data.Add("WC", new PackagingTypeRecord("WC", "Intermediate bulk container, steel"));
                    _data["WC"].numeric = "23 to 26";
                    _data.Add("WD", new PackagingTypeRecord("WD", "Intermediate bulk container, aluminium"));
                    _data["WD"].numeric = "23 to 26";
                    _data.Add("WF", new PackagingTypeRecord("WF", "Intermediate bulk container, metal"));
                    _data["WF"].numeric = "23 to 26";
                    _data.Add("WG", new PackagingTypeRecord("WG", "Intermediate bulk container, steel, pressurised > 10 kpa"));
                    _data["WG"].numeric = "23 to 26";
                    _data.Add("WH", new PackagingTypeRecord("WH", "Intermediate bulk container, aluminium, pressurised > 10 kpa"));
                    _data["WH"].numeric = "23 to 26";
                    _data.Add("WJ", new PackagingTypeRecord("WJ", "Intermediate bulk container, metal, pressure 10 kpa"));
                    _data["WJ"].numeric = "23 to 26";
                    _data.Add("WK", new PackagingTypeRecord("WK", "Intermediate bulk container, steel, liquid"));
                    _data["WK"].numeric = "23 to 26";
                    _data.Add("WL", new PackagingTypeRecord("WL", "Intermediate bulk container, aluminium, liquid"));
                    _data["WL"].numeric = "23 to 26";
                    _data.Add("WM", new PackagingTypeRecord("WM", "Intermediate bulk container, metal, liquid"));
                    _data["WM"].numeric = "23 to 26";
                    _data.Add("WN", new PackagingTypeRecord("WN", "Intermediate bulk container, woven plastic, without coat/liner"));
                    _data["WN"].numeric = "62 to 64";
                    _data.Add("WP", new PackagingTypeRecord("WP", "Intermediate bulk container, woven plastic, coated"));
                    _data["WP"].numeric = "62 to 64";
                    _data.Add("WQ", new PackagingTypeRecord("WQ", "Intermediate bulk container, woven plastic, with liner"));
                    _data["WQ"].numeric = "62 to 64";
                    _data.Add("WR", new PackagingTypeRecord("WR", "Intermediate bulk container, woven plastic, coated and liner"));
                    _data["WR"].numeric = "62 to 64";
                    _data.Add("WS", new PackagingTypeRecord("WS", "Intermediate bulk container, plastic film"));
                    _data["WS"].numeric = "62 to 64";
                    _data.Add("WT", new PackagingTypeRecord("WT", "Intermediate bulk container, textile with out coat/liner"));
                    _data["WT"].numeric = "62 to 64";
                    _data.Add("WU", new PackagingTypeRecord("WU", "Intermediate bulk container, natural wood, with inner liner"));
                    _data["WU"].numeric = "23 to 26";
                    _data.Add("WV", new PackagingTypeRecord("WV", "Intermediate bulk container, textile, coated"));
                    _data["WV"].numeric = "62 to 64";
                    _data.Add("WW", new PackagingTypeRecord("WW", "Intermediate bulk container, textile, with liner"));
                    _data["WW"].numeric = "62 to 64";
                    _data.Add("WX", new PackagingTypeRecord("WX", "Intermediate bulk container, textile, coated and liner"));
                    _data["WX"].numeric = "62 to 64";
                    _data.Add("WY", new PackagingTypeRecord("WY", "Intermediate bulk container, plywood, with inner liner"));
                    _data["WY"].numeric = "23 to 26";
                    _data.Add("WZ", new PackagingTypeRecord("WZ", "Intermediate bulk container, reconstituted wood, with inner liner"));
                    _data["WZ"].numeric = "23 to 26";
                    _data.Add("XA", new PackagingTypeRecord("XA", "Bag, woven plastic, without inner coat/liner"));
                    _data["XA"].numeric = "62 to 64";
                    _data.Add("XB", new PackagingTypeRecord("XB", "Bag, woven plastic, sift proof"));
                    _data["XB"].numeric = "62 to 64";
                    _data.Add("XC", new PackagingTypeRecord("XC", "Bag, woven plastic, water resistant"));
                    _data["XC"].numeric = "62 to 64";
                    _data.Add("XD", new PackagingTypeRecord("XD", "Bag, plastics film"));
                    _data["XD"].numeric = "62 to 64";
                    _data.Add("XF", new PackagingTypeRecord("XF", "Bag, textile, without inner coat/liner"));
                    _data["XF"].numeric = "62 to 64";
                    _data.Add("XG", new PackagingTypeRecord("XG", "Bag, textile, sift proof"));
                    _data["XG"].numeric = "62 to 64";
                    _data.Add("XH", new PackagingTypeRecord("XH", "Bag, textile, water resistant"));
                    _data["XH"].numeric = "62 to 64";
                    _data.Add("XJ", new PackagingTypeRecord("XJ", "Bag, paper, multi-wall"));
                    _data["XJ"].numeric = "62 to 64";
                    _data.Add("XK", new PackagingTypeRecord("XK", "Bag, paper, multi-wall, water resistant"));
                    _data["XK"].numeric = "62 to 64";
                    _data.Add("YA", new PackagingTypeRecord("YA", "Composite packaging, plastic receptacle in steel drum"));
                    _data["YA"].numeric = "33 or 34";
                    _data.Add("YB", new PackagingTypeRecord("YB", "Composite packaging, plastic receptacle in steel crate box"));
                    _data["YB"].numeric = "24 or 25";
                    _data.Add("YC", new PackagingTypeRecord("YC", "Composite packaging, plastic receptacle in aluminium drum"));
                    _data["YC"].numeric = "33 or 34";
                    _data.Add("YD", new PackagingTypeRecord("YD", "Composite packaging, plastic receptacle in aluminium crate"));
                    _data["YD"].numeric = "24 or 25";
                    _data.Add("YF", new PackagingTypeRecord("YF", "Composite packaging, plastic receptacle in wooden box"));
                    _data["YF"].numeric = "24 or 25";
                    _data.Add("YG", new PackagingTypeRecord("YG", "Composite packaging, plastic receptacle in plywood drum"));
                    _data["YG"].numeric = "33 or 34";
                    _data.Add("YH", new PackagingTypeRecord("YH", "Composite packaging, plastic receptacle in plywood box"));
                    _data["YH"].numeric = "24 or 25";
                    _data.Add("YJ", new PackagingTypeRecord("YJ", "Composite packaging, plastic receptacle in fibre drum"));
                    _data["YJ"].numeric = "33 or 34";
                    _data.Add("YK", new PackagingTypeRecord("YK", "Composite packaging, plastic receptacle in fibreboard box"));
                    _data["YK"].numeric = "24 or 25";
                    _data.Add("YL", new PackagingTypeRecord("YL", "Composite packaging, plastic receptacle in plastic drum"));
                    _data["YL"].numeric = "33 or 34";
                    _data.Add("YM", new PackagingTypeRecord("YM", "Composite packaging, plastic receptacle in solid plastic box"));
                    _data["YM"].numeric = "24 or 25";
                    _data.Add("YN", new PackagingTypeRecord("YN", "Composite packaging, glass receptacle in steel drum"));
                    _data["YN"].numeric = "33 or 34";
                    _data.Add("YP", new PackagingTypeRecord("YP", "Composite packaging, glass receptacle in steel crate box"));
                    _data["YP"].numeric = "24 or 25";
                    _data.Add("YQ", new PackagingTypeRecord("YQ", "Composite packaging, glass receptacle in aluminium drum"));
                    _data["YQ"].numeric = "33 or 34";
                    _data.Add("YR", new PackagingTypeRecord("YR", "Composite packaging, glass receptacle in aluminium crate"));
                    _data["YR"].numeric = "24 or 25";
                    _data.Add("YS", new PackagingTypeRecord("YS", "Composite packaging, glass receptacle in wooden box"));
                    _data["YS"].numeric = "24 or 25";
                    _data.Add("YT", new PackagingTypeRecord("YT", "Composite packaging, glass receptacle in plywood drum"));
                    _data["YT"].numeric = "33 or 34";
                    _data.Add("YV", new PackagingTypeRecord("YV", "Composite packaging, glass receptacle in wickerwork hamper"));
                    _data["YV"].numeric = "23";
                    _data.Add("YW", new PackagingTypeRecord("YW", "Composite packaging, glass receptacle in fibre drum"));
                    _data["YW"].numeric = "33 or 34";
                    _data.Add("YX", new PackagingTypeRecord("YX", "Composite packaging, glass receptacle in fibreboard box"));
                    _data["YX"].numeric = "24 or 25";
                    _data.Add("YY", new PackagingTypeRecord("YY", "Composite packaging, glass receptacle in expandable plastic pack"));
                    _data["YY"].numeric = "62 or 63";
                    _data.Add("YZ", new PackagingTypeRecord("YZ", "Composite packaging, glass receptacle in solid plastic pack"));
                    _data["YZ"].numeric = "23 or 24";
                    _data.Add("ZA", new PackagingTypeRecord("ZA", "Intermediate bulk container, paper, multi-wall"));
                    _data["ZA"].numeric = "62 to 64";
                    _data.Add("ZB", new PackagingTypeRecord("ZB", "Bag, large"));
                    _data["ZB"].numeric = "62 to 64";
                    _data.Add("ZC", new PackagingTypeRecord("ZC", "Intermediate bulk container, paper, multi-wall, water resistant"));
                    _data["ZC"].numeric = "62 to 64";
                    _data.Add("ZD", new PackagingTypeRecord("ZD", "Intermediate bulk container, rigid plastic, with structural equipment, solids"));
                    _data["ZD"].numeric = "23 to 26";
                    _data.Add("ZF", new PackagingTypeRecord("ZF", "Intermediate bulk container, rigid plastic, freestanding, solids"));
                    _data["ZF"].numeric = "23 to 26";
                    _data.Add("ZG", new PackagingTypeRecord("ZG", "Intermediate bulk container, rigid plastic, with structural equipment, pressurise" +
                                "d"));
                    _data["ZG"].numeric = "23 to 26";
                    _data.Add("ZH", new PackagingTypeRecord("ZH", "Intermediate bulk container, rigid plastic, freestanding, pressurised"));
                    _data["ZH"].numeric = "23 to 26";
                    _data.Add("ZJ", new PackagingTypeRecord("ZJ", "Intermediate bulk container, rigid plastic, with structural equipment, liquids"));
                    _data["ZJ"].numeric = "23 to 26";
                    _data.Add("ZK", new PackagingTypeRecord("ZK", "Intermediate bulk container, rigid plastic, freestanding, liquids"));
                    _data["ZK"].numeric = "23 to 26";
                    _data.Add("ZL", new PackagingTypeRecord("ZL", "Intermediate bulk container, composite, rigid plastic, solids"));
                    _data["ZL"].numeric = "23 to 26";
                    _data.Add("ZM", new PackagingTypeRecord("ZM", "Intermediate bulk container, composite, flexible plastic, solids"));
                    _data["ZM"].numeric = "62 to 64";
                    _data.Add("ZN", new PackagingTypeRecord("ZN", "Intermediate bulk container, composite, rigid plastic, pressurised"));
                    _data["ZN"].numeric = "23 to 26";
                    _data.Add("ZP", new PackagingTypeRecord("ZP", "Intermediate bulk container, composite, flexible plastic, pressurised"));
                    _data["ZP"].numeric = "62 to 64";
                    _data.Add("ZQ", new PackagingTypeRecord("ZQ", "Intermediate bulk container, composite, rigid plastic, liquids"));
                    _data["ZQ"].numeric = "23 to 26";
                    _data.Add("ZR", new PackagingTypeRecord("ZR", "Intermediate bulk container, composite, flexible plastic, liquids"));
                    _data["ZR"].numeric = "62 to 64";
                    _data.Add("ZS", new PackagingTypeRecord("ZS", "Intermediate bulk container, composite"));
                    _data["ZS"].numeric = "23 to 26 or\r 62 to 64";
                    _data.Add("ZT", new PackagingTypeRecord("ZT", "Intermediate bulk container, fibreboard"));
                    _data["ZT"].numeric = "23 to 26";
                    _data.Add("ZU", new PackagingTypeRecord("ZU", "Intermediate bulk container, flexible"));
                    _data["ZU"].numeric = "23 to 26";
                    _data.Add("ZV", new PackagingTypeRecord("ZV", "Intermediate bulk container, metal, other than steel"));
                    _data["ZV"].numeric = "23 to 26";
                    _data.Add("ZW", new PackagingTypeRecord("ZW", "Intermediate bulk container, natural wood"));
                    _data["ZW"].numeric = "23 to 26";
                    _data.Add("ZX", new PackagingTypeRecord("ZX", "Intermediate bulk container, plywood"));
                    _data["ZX"].numeric = "23 to 26";
                    _data.Add("ZY", new PackagingTypeRecord("ZY", "Intermediate bulk container, reconstituted wood"));
                    _data["ZY"].numeric = "23 to 26";
                    _data.Add("ZZ", new PackagingTypeRecord("ZZ", "Mutually defined"));
                    _data["ZZ"].numeric = "0";
                }
                return _data;
            }
        }
        
        public static IEnumerable<string> GetCodesAll()
        {
            return DATA.Keys;
        }
        
        public static IEnumerable<string> GetCodesAllNotIn<T>()
            where T : struct
        {
            var fields = System.Enum.GetValues(typeof(T));
            if ((fields.Length == 0))
            {
                throw new System.ArgumentOutOfRangeException("fields", "Enum of type T must contain at least one field.");
            }
            var existingCodes = new List<string>();
            for (int i = 0; (i < fields.Length); i = (i + 1))
            {
                var code = GcCodeValueParser.ReadCode(((System.Enum)(fields.GetValue(i))));
                existingCodes.Add(code);
            }
            return DATA.Keys.Except(existingCodes);
        }
        
        public static string GetValue(string code)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or less characters.");
            }
            if ((code.Length < 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or more characters.");
            }
            return DATA[code].VALUE;
        }
        
        public static string GetValue(string code, Func<PackagingTypeRecord, string> selector)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or less characters.");
            }
            if ((code.Length < 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or more characters.");
            }
            return selector(DATA[code]);
        }
        
        public static decimal GetValue(string code, Func<PackagingTypeRecord, decimal> selector)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or less characters.");
            }
            if ((code.Length < 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or more characters.");
            }
            return selector(DATA[code]);
        }
        
        public static int GetValue(string code, Func<PackagingTypeRecord, int> selector)
        {
            if ((code == null))
            {
                throw new System.ArgumentNullException("code");
            }
            if ((code.Length > 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or less characters.");
            }
            if ((code.Length < 2))
            {
                throw new System.ArgumentOutOfRangeException("code", "Code must contain 2 or more characters.");
            }
            return selector(DATA[code]);
        }
        
        /// <summary>
        /// Returns a list of codes with data in selected column that match search text.
        /// Exact matches (equality ignoring cases) are returned first,
        /// then partial matches (always ignoring cases) if forceExactMatch has not been set.
        /// </summary>
        public static IEnumerable<string> GetCodesLike(string text, Func<PackagingTypeRecord, string> selector, bool forceExactMatch)
        {
            if ((text == null))
            {
                throw new System.ArgumentNullException("text");
            }
            var exactMatchingCodes = DATA.Where(x => selector(x.Value) != null && selector(x.Value).ToLowerInvariant() == text.ToLowerInvariant()).Select(x => x.Key);
            if ((forceExactMatch == true))
            {
                return exactMatchingCodes;
            }
            var containMatchingCodes = DATA.Where(x => selector(x.Value) != null && text.ToLowerInvariant().Contains(selector(x.Value).ToLowerInvariant())).Select(x => x.Key);
            var codes = new List<string>();
            codes.AddRange(exactMatchingCodes);
            codes.AddRange(containMatchingCodes.Except(exactMatchingCodes));
            return codes;
        }
        
        public class PackagingTypeRecord
        {
            
            public string code { get; private set; }
            
            public string name { get; private set; }
            
            public string description { get; set; }
            
            public string numeric { get; set; }
            
            public PackagingTypeRecord(string code, string name)
            {
                this.code = code;
                this.name = name;
            }
            
            public string CODE
            {
                get
                {
                    return this.code;
                }
            }
            
            public string VALUE
            {
                get
                {
                    return this.name;
                }
            }
        }
    }
}
