//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITela.Gc
{
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("https://raw.githubusercontent.com/ericdes/tela-interface/master/TELA-1.0/Archived" +
        "RecordStatusCode.gc", IsRestriction=true)]
    [GcEnumField("code", GcEnumPart.Code, GcEnumPart.Value, GcEnumPart.Field, DataType="StringValue<StringMax15>", Min=6, Max=10)]
    [GcEnumField("description", GcEnumPart.Comments, DataType="StringValue<StringMax200>", Min=12, Max=105)]
    public enum ArchivedRecordStatus
    {
        
        /// <summary>
        /// May be used.
        /// </summary>
        [GcCodeValue("Active", "Active")]
        Active,
        
        /// <summary>
        /// Must not be use -- no longer used or required, but kept to avoid breaking existing links or dependencies.
        /// </summary>
        [GcCodeValue("Inactive", "Inactive")]
        Inactive,
        
        /// <summary>
        /// Should not be used -- to be inactivated or deleted in the future.
        /// </summary>
        [GcCodeValue("Deprecated", "Deprecated")]
        Deprecated,
    }
}
